In [1]:
import pandas as pd

In [2]:
jusice_dataframe=pd.read_excel(r"C:\Users\Rahhal\Desktop\DataSets\Excel Data\Juice_Sales_Dataset.xlsx")

In [3]:
jusice_dataframe

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
0,Store_001,Orange Juice,January 2024,1,121,4.89,1365,592.25,3.3,0.66
1,Store_001,Orange Juice,February 2024,2,137,3.83,1410,525.37,3.3,0.86
2,Store_001,Orange Juice,March 2024,3,137,5.83,1454,798.68,3.4,0.67
3,Store_001,Orange Juice,April 2024,4,253,4.95,1496,1251.49,3.0,0.61
4,Store_001,Orange Juice,May 2024,5,219,2.69,1579,588.38,4.9,0.69
...,...,...,...,...,...,...,...,...,...,...
1915,Store_010,Papaya Juice,August 2024,8,193,6.39,821,1234.19,3.5,0.91
1916,Store_010,Papaya Juice,September 2024,9,155,5.75,671,890.93,3.6,0.67
1917,Store_010,Papaya Juice,October 2024,10,96,4.39,739,421.15,4.0,0.89
1918,Store_010,Papaya Juice,November 2024,11,145,3.87,728,560.59,4.9,0.80
1919,Store_010,Papaya Juice,December 2024,12,229,3.79,1078,868.81,3.0,0.80

## Displaed all dataFrame

In [4]:
pd.options.display.max_rows=1920

In [5]:
jusice_dataframe

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
0,Store_001,Orange Juice,January 2024,1,121,4.89,1365,592.25,3.3,0.66
1,Store_001,Orange Juice,February 2024,2,137,3.83,1410,525.37,3.3,0.86
2,Store_001,Orange Juice,March 2024,3,137,5.83,1454,798.68,3.4,0.67
3,Store_001,Orange Juice,April 2024,4,253,4.95,1496,1251.49,3.0,0.61
4,Store_001,Orange Juice,May 2024,5,219,2.69,1579,588.38,4.9,0.69
5,Store_001,Orange Juice,June 2024,6,239,3.30,1137,788.39,4.0,0.84
6,Store_001,Orange Juice,July 2024,7,100,5.22,946,522.12,3.9,0.61
7,Store_001,Orange Juice,August 2024,8,63,5.73,1184,361.22,3.6,0.64
8,Store_001,Orange Juice,September 2024,9,160,5.23,1022,837.29,4.2,0.93
9,Store_001,Orange Juice,October 2024,10,130,3.54,875,459.57,4.3,0.72
10,Store_001,Orange Juice,November 2024,11,155,4.77,1165,739.47,3.1,0.94
11,Store_001,Orange Juice,December 2024,12,251,6.08,1332,1525.91,4.2,0.97
12,Store_001,Apple Juice,January 2024,1,298,6.34,1129,1890.72,4.7,0.90
13,Store_001,Apple Juice,February 2024,2,73,3.93,1222,286.67,3.6,0.82
14,Store_001,Apple Juice,March 2024,3,64,3.16,1063,202.31,3.0,0.77
15,Store_001,Apple Juice,April 2024,4,185,2.52,1152,466.59,4.6,0.88
16,Store_001,Apple Juice,May 2024,5,82,4.92,1198,403.75,4.9,0.86
17,Store_001,Apple Juice,June 2024,6,250,4.99,1113,1248.30,3.7,0.63
18,Store_001,Apple Juice,July 2024,7,265,5.16,750,1368.38,4.2,0.71
19,Store_001,Apple Juice,August 2024,8,276,2.98,724,822.03,4.4,0.90
20,Store_001,Apple Juice,September 2024,9,191,4.48,684,854.76,4.0,0.77
21,Store_001,Apple Juice,October 2024,10,254,3.31,572,839.95,4.8,0.79
22,Store_001,Apple Juice,November 2024,11,181,6.13,832,1109.58,3.5,0.76
23,Store_001,Apple Juice,December 2024,12,85,6.27,1052,533.07,4.2,0.88
24,Store_001,Mango Juice,January 2024,1,94,3.68,3125,346.16,3.2,0.78
25,Store_001,Mango Juice,February 2024,2,133,6.07,2592,807.34,4.1,0.92
26,Store_001,Mango Juice,March 2024,3,280,6.13,3492,1715.65,3.5,0.86
27,Store_001,Mango Juice,April 2024,4,254,5.94,2337,1509.50,3.0,0.80
28,Store_001,Mango Juice,May 2024,5,214,5.27,2578,1127.73,3.5,0.70
29,Store_001,Mango Juice,June 2024,6,209,4.58,2011,956.21,4.4,0.75
30,Store_001,Mango Juice,July 2024,7,101,3.49,2343,352.24,4.4,0.88
31,Store_001,Mango Juice,August 2024,8,233,2.65,1474,616.88,4.2,0.80
32,Store_001,Mango Juice,September 2024,9,278,3.88,1332,1078.72,4.3,0.87
33,Store_001,Mango Juice,October 2024,10,267,6.44,1737,1720.17,3.5,0.87
34,Store_001,Mango Juice,November 2024,11,172,3.47,2177,596.61,4.6,0.79
35,Store_001,Mango Juice,December 2024,12,263,4.64,2767,1221.13,3.2,0.93
36,Store_001,Pineapple Juice,January 2024,1,257,2.66,1900,684.42,4.2,0.87
37,Store_001,Pineapple Juice,February 2024,2,244,5.74,1673,1400.07,3.7,0.64
38,Store_001,Pineapple Juice,March 2024,3,217,4.05,2518,878.19,4.9,0.66
39,Store_001,Pineapple Juice,April 2024,4,266,3.34,1942,887.45,4.1,0.88
40,Store_001,Pineapple Juice,May 2024,5,193,5.77,1688,1113.40,4.1,0.81
41,Store_001,Pineapple Juice,June 2024,6,97,6.36,1476,617.08,4.1,0.95
42,Store_001,Pineapple Juice,July 2024,7,282,3.90,1225,1098.91,4.5,0.96
43,Store_001,Pineapple Juice,August 2024,8,169,6.05,1407,1022.63,4.7,0.97
44,Store_001,Pineapple Juice,September 2024,9,153,4.93,1284,753.63,3.0,0.64
45,Store_001,Pineapple Juice,October 2024,10,142,3.64,1298,516.27,3.6,0.79
46,Store_001,Pineapple Juice,November 2024,11,238,3.40,1371,808.50,4.4,0.69
47,Store_001,Pineapple Juice,December 2024,12,197,3.97,1531,781.28,4.5,0.89
48,Store_001,Watermelon Juice,January 2024,1,253,4.54,1345,1147.42,4.3,0.70
49,Store_001,Watermelon Juice,February 2024,2,279,4.07,1486,1136.20,4.8,0.85
50,Store_001,Watermelon Juice,March 2024,3,79,5.08,1655,401.35,4.3,0.95
51,Store_001,Watermelon Juice,April 2024,4,97,3.62,1280,351.44,3.0,0.86
52,Store_001,Watermelon Juice,May 2024,5,269,4.38,1140,1178.16,3.6,0.95
53,Store_001,Watermelon Juice,June 2024,6,86,6.21,1251,534.34,3.9,0.99
54,Store_001,Watermelon Juice,July 2024,7,274,2.80,1147,767.58,3.6,0.68
55,Store_001,Watermelon Juice,August 2024,8,116,3.18,765,368.64,4.1,0.97
56,Store_001,Watermelon Juice,September 2024,9,153,2.78,859,425.59,3.4,0.87
57,Store_001,Watermelon Juice,October 2024,10,176,4.57,795,804.90,4.8,0.90
58,Store_001,Watermelon Juice,November 2024,11,92,5.34,1044,490.88,4.1,0.72
59,Store_001,Watermelon Juice,December 2024,12,99,5.97,1102,590.86,4.8,0.80
60,Store_001,Strawberry Juice,January 2024,1,114,2.78,688,317.35,3.8,0.62
61,Store_001,Strawberry Juice,February 2024,2,192,4.00,778,768.45,3.2,0.83
62,Store_001,Strawberry Juice,March 2024,3,202,3.12,566,630.27,5.0,0.94
63,Store_001,Strawberry Juice,April 2024,4,98,2.65,771,259.64,4.6,0.74
64,Store_001,Strawberry Juice,May 2024,5,274,5.81,523,1592.34,3.5,0.99
65,Store_001,Strawberry Juice,June 2024,6,55,2.71,525,148.87,4.1,0.82
66,Store_001,Strawberry Juice,July 2024,7,101,3.03,479,306.13,4.9,0.89
67,Store_001,Strawberry Juice,August 2024,8,169,3.58,323,605.58,3.9,0.63
68,Store_001,Strawberry Juice,September 2024,9,166,2.82,303,468.70,3.9,0.88
69,Store_001,Strawberry Juice,October 2024,10,171,3.13,326,534.50,3.5,0.82
70,Store_001,Strawberry Juice,November 2024,11,281,6.24,493,1753.01,4.3,0.81
71,Store_001,Strawberry Juice,December 2024,12,118,4.95,568,583.73,3.8,0.70
72,Store_001,Lemon Juice,January 2024,1,135,2.56,2163,345.27,3.2,0.62
73,Store_001,Lemon Juice,February 2024,2,287,6.42,2240,1841.98,3.4,0.61
74,Store_001,Lemon Juice,March 2024,3,134,4.39,3131,588.78,3.3,0.77
75,Store_001,Lemon Juice,April 2024,4,59,6.30,2633,371.50,4.8,0.70
76,Store_001,Lemon Juice,May 2024,5,196,4.51,2020,884.46,4.7,0.86
77,Store_001,Lemon Juice,June 2024,6,73,6.28,1885,458.12,4.9,0.95
78,Store_001,Lemon Juice,July 2024,7,133,4.80,1953,638.65,3.8,0.86
79,Store_001,Lemon Juice,August 2024,8,228,5.78,1585,1318.42,4.3,0.93
80,Store_001,Lemon Juice,September 2024,9,92,3.28,1617,302.05,3.1,0.64
81,Store_001,Lemon Juice,October 2024,10,292,4.97,1302,1452.12,3.7,0.86
82,Store_001,Lemon Juice,November 2024,11,251,2.59,1767,650.87,4.6,0.71
83,Store_001,Lemon Juice,December 2024,12,294,3.89,1846,1144.64,4.9,0.62
84,Store_001,Grape Juice,January 2024,1,298,4.69,1583,1398.18,3.8,0.83
85,Store_001,Grape Juice,February 2024,2,148,4.15,1594,614.27,3.7,0.91
86,Store_001,Grape Juice,March 2024,3,239,4.75,1494,1134.64,3.5,0.87
87,Store_001,Grape Juice,April 2024,4,148,2.91,1695,431.05,4.8,0.80
88,Store_001,Grape Juice,May 2024,5,135,3.69,1596,498.22,3.2,0.62
89,Store_001,Grape Juice,June 2024,6,196,2.87,1453,561.57,3.6,0.98
90,Store_001,Grape Juice,July 2024,7,132,4.47,1231,590.32,3.2,0.64
91,Store_001,Grape Juice,August 2024,8,229,5.19,946,1188.53,4.5,0.92
92,Store_001,Grape Juice,September 2024,9,158,6.22,959,983.35,4.9,1.00
93,Store_001,Grape Juice,October 2024,10,212,6.05,747,1282.77,3.7,0.65
94,Store_001,Grape Juice,November 2024,11,123,5.85,894,719.29,4.7,0.94
95,Store_001,Grape Juice,December 2024,12,217,2.79,1191,605.66,4.6,0.88
96,Store_001,Carrot Juice,January 2024,1,215,6.45,2358,1386.01,3.7,0.75
97,Store_001,Carrot Juice,February 2024,2,120,6.44,2891,773.28,4.5,0.75
98,Store_001,Carrot Juice,March 2024,3,238,4.01,2210,954.84,4.4,0.70
99,Store_001,Carrot Juice,April 2024,4,175,4.47,2395,782.34,3.0,0.79
100,Store_001,Carrot Juice,May 2024,5,269,5.57,1929,1498.00,4.6,0.90
101,Store_001,Carrot Juice,June 2024,6,141,6.35,2187,895.17,3.7,0.71
102,Store_001,Carrot Juice,July 2024,7,215,4.25,1989,912.75,4.6,0.99
103,Store_001,Carrot Juice,August 2024,8,96,6.06,1543,582.20,4.1,1.00
104,Store_001,Carrot Juice,September 2024,9,276,5.28,1184,1457.73,3.2,0.67
105,Store_001,Carrot Juice,October 2024,10,192,4.32,1338,829.09,4.3,0.83
106,Store_001,Carrot Juice,November 2024,11,234,6.16,2012,1441.68,4.9,0.62
107,Store_001,Carrot Juice,December 2024,12,201,4.98,1953,1001.09,3.6,0.68
108,Store_001,Pomegranate Juice,January 2024,1,109,4.83,647,526.97,3.2,0.99
109,Store_001,Pomegranate Juice,February 2024,2,295,2.63,886,775.63,3.6,0.76
110,Store_001,Pomegranate Juice,March 2024,3,289,3.15,797,910.49,4.8,0.93
111,Store_001,Pomegranate Juice,April 2024,4,246,4.95,875,1218.60,3.8,0.97
112,Store_001,Pomegranate Juice,May 2024,5,158,3.16,776,499.18,3.8,0.91
113,Store_001,Pomegranate Juice,June 2024,6,288,3.10,584,893.28,4.2,0.75
114,Store_001,Pomegranate Juice,July 2024,7,76,4.78,594,363.00,3.1,0.61
115,Store_001,Pomegranate Juice,August 2024,8,198,2.73,372,539.65,4.7,0.93
116,Store_001,Pomegranate Juice,September 2024,9,151,6.15,494,929.05,4.2,0.89
117,Store_001,Pomegranate Juice,October 2024,10,132,3.49,480,460.60,3.9,0.65
118,Store_001,Pomegranate Juice,November 2024,11,254,3.33,591,845.54,4.8,0.90
119,Store_001,Pomegranate Juice,December 2024,12,144,2.95,482,425.41,4.3,0.81
120,Store_001,Guava Juice,January 2024,1,99,5.91,3470,584.96,4.1,0.82
121,Store_001,Guava Juice,February 2024,2,106,4.86,3863,515.14,4.0,0.77
122,Store_001,Guava Juice,March 2024,3,191,5.32,3858,1015.42,3.4,0.65
123,Store_001,Guava Juice,April 2024,4,87,4.93,2705,429.11,4.3,0.82
124,Store_001,Guava Juice,May 2024,5,275,3.89,2563,1070.58,4.0,0.91
125,Store_001,Guava Juice,June 2024,6,296,4.59,2554,1359.95,4.4,0.92
126,Store_001,Guava Juice,July 2024,7,194,4.47,2228,866.88,3.5,0.78
127,Store_001,Guava Juice,August 2024,8,102,3.89,2351,396.74,3.4,0.83
128,Store_001,Guava Juice,September 2024,9,160,3.02,1747,482.48,3.3,0.66
129,Store_001,Guava Juice,October 2024,10,57,3.22,1687,183.56,4.4,0.76
130,Store_001,Guava Juice,November 2024,11,204,5.17,2604,1054.73,3.3,0.68
131,Store_001,Guava Juice,December 2024,12,54,3.88,2175,209.54,3.7,0.61
132,Store_001,Passion Fruit Juice,January 2024,1,95,3.96,3012,375.92,4.0,0.88
133,Store_001,Passion Fruit Juice,February 2024,2,298,4.42,2856,1318.53,4.4,0.80
134,Store_001,Passion Fruit Juice,March 2024,3,97,2.74,3118,266.20,3.6,0.92
135,Store_001,Passion Fruit Juice,April 2024,4,229,3.34,3850,764.26,3.7,0.79
136,Store_001,Passion Fruit Juice,May 2024,5,264,4.63,3348,1221.02,4.4,0.62
137,Store_001,Passion Fruit Juice,June 2024,6,164,5.35,2388,877.96,4.8,0.80
138,Store_001,Passion Fruit Juice,July 2024,7,286,5.97,2393,1707.09,3.7,0.76
139,Store_001,Passion Fruit Juice,August 2024,8,168,4.01,1732,673.53,3.0,0.73
140,Store_001,Passion Fruit Juice,September 2024,9,267,4.64,1721,1239.24,3.5,0.74
141,Store_001,Passion Fruit Juice,October 2024,10,187,5.66,2036,1057.80,4.0,0.63
142,Store_001,Passion Fruit Juice,November 2024,11,83,4.73,2398,392.67,4.2,0.83
143,Store_001,Passion Fruit Juice,December 2024,12,150,3.95,2645,592.85,4.3,0.83
144,Store_001,Peach Juice,January 2024,1,247,4.92,2844,1216.01,3.5,0.64
145,Store_001,Peach Juice,February 2024,2,296,4.45,2685,1317.57,4.7,0.64
146,Store_001,Peach Juice,March 2024,3,201,6.09,3611,1223.50,3.2,0.81
147,Store_001,Peach Juice,April 2024,4,85,6.49,3006,551.57,4.8,0.83
148,Store_001,Peach Juice,May 2024,5,128,5.77,3321,738.34,3.5,0.67
149,Store_001,Peach Juice,June 2024,6,234,5.37,2641,1257.48,4.1,0.79
150,Store_001,Peach Juice,July 2024,7,182,3.25,2388,591.17,3.6,0.77
151,Store_001,Peach Juice,August 2024,8,162,4.62,1837,748.34,4.4,0.91
152,Store_001,Peach Juice,September 2024,9,175,3.12,1446,545.55,4.0,0.81
153,Store_001,Peach Juice,October 2024,10,227,4.32,1503,979.98,4.1,0.82
154,Store_001,Peach Juice,November 2024,11,217,5.74,1852,1245.47,3.5,0.87
155,Store_001,Peach Juice,December 2024,12,252,4.39,2732,1106.95,4.2,0.92
156,Store_001,Blueberry Juice,January 2024,1,111,5.48,2180,608.71,3.8,0.97
157,Store_001,Blueberry Juice,February 2024,2,211,3.22,2438,680.46,3.1,0.90
158,Store_001,Blueberry Juice,March 2024,3,113,5.63,2166,635.74,4.7,0.90
159,Store_001,Blueberry Juice,April 2024,4,84,3.16,2282,265.19,4.6,0.87
160,Store_001,Blueberry Juice,May 2024,5,181,3.76,1877,681.43,4.2,0.87
161,Store_001,Blueberry Juice,June 2024,6,153,4.01,1586,613.19,3.9,0.72
162,Store_001,Blueberry Juice,July 2024,7,192,4.81,1511,923.51,3.7,0.76
163,Store_001,Blueberry Juice,August 2024,8,102,6.13,1212,624.84,4.2,0.65
164,Store_001,Blueberry Juice,September 2024,9,184,5.42,1331,997.68,4.4,0.67
165,Store_001,Blueberry Juice,October 2024,10,82,4.63,1379,379.98,4.8,0.92
166,Store_001,Blueberry Juice,November 2024,11,146,5.33,1183,777.88,4.6,0.66
167,Store_001,Blueberry Juice,December 2024,12,115,5.55,1426,638.23,4.8,0.74
168,Store_001,Cranberry Juice,January 2024,1,277,4.33,2361,1198.86,4.2,0.80
169,Store_001,Cranberry Juice,February 2024,2,206,3.42,3112,703.90,4.4,0.89
170,Store_001,Cranberry Juice,March 2024,3,292,4.76,3340,1390.51,4.4,0.84
171,Store_001,Cranberry Juice,April 2024,4,123,3.87,3464,476.02,3.5,0.77
172,Store_001,Cranberry Juice,May 2024,5,156,3.11,2559,485.69,4.2,0.80
173,Store_001,Cranberry Juice,June 2024,6,160,5.40,2540,864.70,4.2,0.64
174,Store_001,Cranberry Juice,July 2024,7,182,6.19,2413,1126.58,4.4,0.66
175,Store_001,Cranberry Juice,August 2024,8,171,2.78,1855,474.64,3.2,0.64
176,Store_001,Cranberry Juice,September 2024,9,60,4.30,1934,258.20,3.2,0.99
177,Store_001,Cranberry Juice,October 2024,10,231,5.85,2044,1351.34,3.7,0.72
178,Store_001,Cranberry Juice,November 2024,11,192,4.10,1841,786.43,3.1,0.73
179,Store_001,Cranberry Juice,December 2024,12,166,4.91,2726,815.87,3.2,0.77
180,Store_001,Papaya Juice,January 2024,1,179,4.36,2854,780.94,4.0,0.97
181,Store_001,Papaya Juice,February 2024,2,236,4.31,2770,1017.10,3.3,0.67
182,Store_001,Papaya Juice,March 2024,3,247,2.64,2760,650.97,3.6,0.91
183,Store_001,Papaya Juice,April 2024,4,203,2.55,2438,518.13,4.3,0.67
184,Store_001,Papaya Juice,May 2024,5,226,4.73,2894,1068.80,4.7,0.81
185,Store_001,Papaya Juice,June 2024,6,120,4.88,1856,585.78,3.1,0.90
186,Store_001,Papaya Juice,July 2024,7,260,3.90,1596,1013.36,3.9,0.85
187,Store_001,Papaya Juice,August 2024,8,193,4.76,1495,918.56,3.1,0.91
188,Store_001,Papaya Juice,September 2024,9,243,4.64,1459,1126.99,4.0,0.80
189,Store_001,Papaya Juice,October 2024,10,181,3.23,1739,584.22,4.7,0.98
190,Store_001,Papaya Juice,November 2024,11,251,6.09,1714,1528.52,4.1,0.92
191,Store_001,Papaya Juice,December 2024,12,81,5.36,2532,434.48,4.3,0.61
192,Store_002,Orange Juice,January 2024,1,236,4.52,2420,1067.20,4.2,0.74
193,Store_002,Orange Juice,February 2024,2,100,5.11,3053,511.10,3.5,0.64
194,Store_002,Orange Juice,March 2024,3,127,4.91,2750,623.92,4.6,0.99
195,Store_002,Orange Juice,April 2024,4,231,3.32,3498,766.91,3.6,0.96
196,Store_002,Orange Juice,May 2024,5,56,5.44,2183,304.84,4.7,0.65
197,Store_002,Orange Juice,June 2024,6,78,4.19,2713,326.48,4.8,0.93
198,Store_002,Orange Juice,July 2024,7,283,5.80,1877,1641.52,3.7,0.61
199,Store_002,Orange Juice,August 2024,8,86,4.14,1976,355.84,4.1,0.77
200,Store_002,Orange Juice,September 2024,9,293,6.40,1514,1874.67,4.6,0.65
201,Store_002,Orange Juice,October 2024,10,108,6.08,1791,656.45,4.6,0.77
202,Store_002,Orange Juice,November 2024,11,63,5.47,1621,344.41,4.4,0.76
203,Store_002,Orange Juice,December 2024,12,71,5.84,2092,414.62,5.0,0.81
204,Store_002,Apple Juice,January 2024,1,195,4.62,1210,900.64,4.6,0.80
205,Store_002,Apple Juice,February 2024,2,214,5.11,1358,1092.62,4.7,0.68
206,Store_002,Apple Juice,March 2024,3,262,3.55,1363,931.34,3.5,0.89
207,Store_002,Apple Juice,April 2024,4,286,5.16,1478,1475.80,3.4,0.97
208,Store_002,Apple Juice,May 2024,5,269,5.58,1450,1502.00,3.8,0.74
209,Store_002,Apple Juice,June 2024,6,242,2.83,1543,685.15,4.2,0.70
210,Store_002,Apple Juice,July 2024,7,89,4.25,1059,378.14,4.8,0.89
211,Store_002,Apple Juice,August 2024,8,103,4.40,1007,453.63,4.3,0.97
212,Store_002,Apple Juice,September 2024,9,82,3.58,997,293.53,4.1,0.66
213,Store_002,Apple Juice,October 2024,10,130,4.49,1097,583.11,4.2,0.73
214,Store_002,Apple Juice,November 2024,11,294,3.88,1228,1140.00,3.7,0.77
215,Store_002,Apple Juice,December 2024,12,153,4.24,1410,648.61,3.5,0.93
216,Store_002,Mango Juice,January 2024,1,228,3.59,1613,818.20,4.2,0.74
217,Store_002,Mango Juice,February 2024,2,98,3.05,1846,298.63,4.9,0.78
218,Store_002,Mango Juice,March 2024,3,111,6.33,1990,702.93,4.5,0.86
219,Store_002,Mango Juice,April 2024,4,278,5.27,2435,1464.81,4.7,0.70
220,Store_002,Mango Juice,May 2024,5,192,5.27,2006,1012.36,3.1,0.87
221,Store_002,Mango Juice,June 2024,6,65,6.20,1432,403.06,3.4,0.83
222,Store_002,Mango Juice,July 2024,7,63,2.98,1736,187.87,4.5,0.68
223,Store_002,Mango Juice,August 2024,8,108,6.28,1097,677.92,3.9,0.94
224,Store_002,Mango Juice,September 2024,9,195,4.59,1395,895.00,4.3,0.86
225,Store_002,Mango Juice,October 2024,10,157,2.98,1226,468.22,3.2,0.88
226,Store_002,Mango Juice,November 2024,11,232,4.12,1393,955.36,4.1,0.92
227,Store_002,Mango Juice,December 2024,12,263,3.78,1778,992.83,4.3,0.95
228,Store_002,Pineapple Juice,January 2024,1,243,2.60,2579,631.22,4.7,0.61
229,Store_002,Pineapple Juice,February 2024,2,190,4.04,2823,766.81,4.9,0.63
230,Store_002,Pineapple Juice,March 2024,3,78,5.57,2036,434.36,3.8,0.79
231,Store_002,Pineapple Juice,April 2024,4,233,3.59,2580,835.71,3.8,0.64
232,Store_002,Pineapple Juice,May 2024,5,133,5.45,2094,724.89,3.5,0.64
233,Store_002,Pineapple Juice,June 2024,6,207,5.91,1835,1223.64,4.4,0.84
234,Store_002,Pineapple Juice,July 2024,7,230,6.45,1509,1483.70,3.9,0.75
235,Store_002,Pineapple Juice,August 2024,8,189,6.33,1546,1195.55,4.6,0.70
236,Store_002,Pineapple Juice,September 2024,9,88,6.02,1412,529.45,4.9,0.79
237,Store_002,Pineapple Juice,October 2024,10,202,5.47,1508,1105.63,3.1,0.76
238,Store_002,Pineapple Juice,November 2024,11,103,4.93,1880,507.89,4.0,0.69
239,Store_002,Pineapple Juice,December 2024,12,267,2.65,1696,706.73,4.9,0.93
240,Store_002,Watermelon Juice,January 2024,1,264,6.04,2777,1593.28,4.9,1.00
241,Store_002,Watermelon Juice,February 2024,2,283,4.56,2515,1290.76,4.0,1.00
242,Store_002,Watermelon Juice,March 2024,3,276,3.40,3459,937.78,3.4,0.81
243,Store_002,Watermelon Juice,April 2024,4,191,5.94,3000,1134.64,3.9,0.76
244,Store_002,Watermelon Juice,May 2024,5,78,6.05,2400,472.29,4.9,0.94
245,Store_002,Watermelon Juice,June 2024,6,89,6.23,2580,554.15,4.5,0.71
246,Store_002,Watermelon Juice,July 2024,7,87,3.54,1758,307.89,4.4,0.80
247,Store_002,Watermelon Juice,August 2024,8,109,2.94,1414,320.23,4.8,1.00
248,Store_002,Watermelon Juice,September 2024,9,94,4.42,1325,415.70,4.2,0.93
249,Store_002,Watermelon Juice,October 2024,10,147,4.68,1596,687.24,4.7,0.89
250,Store_002,Watermelon Juice,November 2024,11,129,5.13,1968,662.26,4.7,0.95
251,Store_002,Watermelon Juice,December 2024,12,156,3.45,2487,538.94,4.9,0.64
252,Store_002,Strawberry Juice,January 2024,1,182,6.02,2989,1096.27,4.7,0.61
253,Store_002,Strawberry Juice,February 2024,2,187,5.78,4227,1080.82,3.5,0.96
254,Store_002,Strawberry Juice,March 2024,3,51,5.83,3089,297.26,4.0,0.60
255,Store_002,Strawberry Juice,April 2024,4,95,3.81,3421,361.54,4.1,0.65
256,Store_002,Strawberry Juice,May 2024,5,241,4.66,3245,1123.05,4.6,0.64
257,Store_002,Strawberry Juice,June 2024,6,123,4.23,3278,520.16,4.7,0.76
258,Store_002,Strawberry Juice,July 2024,7,86,2.91,2200,250.26,4.9,0.88
259,Store_002,Strawberry Juice,August 2024,8,268,3.17,1817,848.36,4.5,0.88
260,Store_002,Strawberry Juice,September 2024,9,71,4.98,2056,353.84,3.1,0.95
261,Store_002,Strawberry Juice,October 2024,10,78,4.28,2613,334.14,4.3,0.84
262,Store_002,Strawberry Juice,November 2024,11,78,2.59,2406,201.90,3.6,0.80
263,Store_002,Strawberry Juice,December 2024,12,107,2.50,3290,267.94,3.3,0.79
264,Store_002,Lemon Juice,January 2024,1,190,5.92,1132,1124.20,4.1,0.93
265,Store_002,Lemon Juice,February 2024,2,81,2.83,1175,229.19,4.4,0.86
266,Store_002,Lemon Juice,March 2024,3,130,6.35,1199,825.88,3.1,0.89
267,Store_002,Lemon Juice,April 2024,4,150,5.05,1488,758.12,3.8,0.71
268,Store_002,Lemon Juice,May 2024,5,50,3.78,1393,189.15,4.4,0.90
269,Store_002,Lemon Juice,June 2024,6,290,5.11,893,1480.93,3.7,0.95
270,Store_002,Lemon Juice,July 2024,7,121,3.14,853,379.57,3.4,0.64
271,Store_002,Lemon Juice,August 2024,8,76,5.88,647,446.81,4.5,0.85
272,Store_002,Lemon Juice,September 2024,9,230,6.15,605,1413.89,4.9,0.67
273,Store_002,Lemon Juice,October 2024,10,271,2.97,739,804.66,3.3,0.87

## Analyizing Market Performance : Revenue & Customer_Satisfaction for "Pineapple Juice" And "Apple Juice"

In [6]:
jusice1=jusice_dataframe[(jusice_dataframe["Juice_Type"]=="Apple Juice")&(jusice_dataframe["Monthly_Sales"]>1200)&(jusice_dataframe["Customer_Satisfaction"]>4.7)|(jusice_dataframe["Juice_Type"]=="Pineapple Juice")&(jusice_dataframe["Monthly_Sales"]>1200)&(jusice_dataframe["Customer_Satisfaction"]>4.7)]

In [7]:
jusice1

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
38,Store_001,Pineapple Juice,March 2024,3,217,4.05,2518,878.19,4.9,0.66
229,Store_002,Pineapple Juice,February 2024,2,190,4.04,2823,766.81,4.9,0.63
236,Store_002,Pineapple Juice,September 2024,9,88,6.02,1412,529.45,4.9,0.79
239,Store_002,Pineapple Juice,December 2024,12,267,2.65,1696,706.73,4.9,0.93
806,Store_005,Pineapple Juice,March 2024,3,137,2.62,1549,359.00,4.9,0.87
808,Store_005,Pineapple Juice,May 2024,5,87,6.29,1300,547.11,4.8,0.90
981,Store_006,Apple Juice,October 2024,10,136,3.77,1252,512.61,4.8,0.62
997,Store_006,Pineapple Juice,February 2024,2,61,3.93,1285,239.50,4.8,0.62
1360,Store_008,Apple Juice,May 2024,5,272,4.04,3109,1097.54,4.9,0.66
1361,Store_008,Apple Juice,June 2024,6,153,5.97,2492,912.99,4.8,0.97
1367,Store_008,Apple Juice,December 2024,12,225,4.50,2606,1013.29,5.0,0.64
1388,Store_008,Pineapple Juice,September 2024,9,85,5.89,1346,500.98,4.8,0.82
1583,Store_009,Pineapple Juice,December 2024,12,50,5.83,1217,291.64,4.9,0.85
1744,Store_010,Apple Juice,May 2024,5,90,5.25,1610,472.27,4.8,0.84
1768,Store_010,Pineapple Juice,May 2024,5,191,4.04,2954,772.52,4.9,0.96

## Descending order from most-selling to least-selling during the Month

In [9]:
decsending=jusice_dataframe.sort_values(by="Monthly_Sales",ascending=False)

In [10]:
decsending

       Store_ID           Juice_Type           Month  Month_Number  \
374   Store_002         Papaya Juice      March 2024             3
542   Store_003      Blueberry Juice      March 2024             3
685   Store_004    Pomegranate Juice   February 2024             2
1489  Store_008          Peach Juice   February 2024             2
782   Store_005          Apple Juice      March 2024             3
253   Store_002     Strawberry Juice   February 2024             2
1106  Store_006          Peach Juice      March 2024             3
1491  Store_008          Peach Juice      April 2024             4
687   Store_004    Pomegranate Juice      April 2024             4
554   Store_003      Cranberry Juice      March 2024             3
663   Store_004          Grape Juice      April 2024             4
757   Store_004         Papaya Juice   February 2024             2
1875  Store_010          Peach Juice      April 2024             4
337   Store_002          Peach Juice   February 2024             2
553   Store_003      Cranberry Juice   February 2024             2
780   Store_005          Apple Juice    January 2024             1
1140  Store_006         Papaya Juice    January 2024             1
291   Store_002         Carrot Juice      April 2024             4
1142  Store_006         Papaya Juice      March 2024             3
1513  Store_008      Cranberry Juice   February 2024             2
1488  Store_008          Peach Juice    January 2024             1
552   Store_003      Cranberry Juice    January 2024             1
121   Store_001          Guava Juice   February 2024             2
122   Store_001          Guava Juice      March 2024             3
686   Store_004    Pomegranate Juice      March 2024             3
135   Store_001  Passion Fruit Juice      April 2024             4
758   Store_004         Papaya Juice      March 2024             3
1144  Store_006         Papaya Juice        May 2024             5
1105  Store_006          Peach Juice   February 2024             2
1141  Store_006         Papaya Juice   February 2024             2
1514  Store_008      Cranberry Juice      March 2024             3
1095  Store_006  Passion Fruit Juice      April 2024             4
662   Store_004          Grape Juice      March 2024             3
376   Store_002         Papaya Juice        May 2024             5
784   Store_005          Apple Juice        May 2024             5
661   Store_004          Grape Juice   February 2024             2
781   Store_005          Apple Juice   February 2024             2
336   Store_002          Peach Juice    January 2024             1
673   Store_004         Carrot Juice   February 2024             2
530   Store_003          Peach Juice      March 2024             3
759   Store_004         Papaya Juice      April 2024             4
340   Store_002          Peach Juice        May 2024             5
1874  Store_010          Peach Juice      March 2024             3
372   Store_002         Papaya Juice    January 2024             1
146   Store_001          Peach Juice      March 2024             3
698   Store_004          Guava Juice      March 2024             3
1094  Store_006  Passion Fruit Juice      March 2024             3
373   Store_002         Papaya Juice   February 2024             2
1096  Store_006  Passion Fruit Juice        May 2024             5
1753  Store_010          Mango Juice   February 2024             2
383   Store_002         Papaya Juice   December 2024            12
1752  Store_010          Mango Juice    January 2024             1
939   Store_005      Cranberry Juice      April 2024             4
1477  Store_008  Passion Fruit Juice   February 2024             2
543   Store_003      Blueberry Juice      April 2024             4
195   Store_002         Orange Juice      April 2024             4
432   Store_003     Watermelon Juice    January 2024             1
26    Store_001          Mango Juice      March 2024             3
674   Store_004         Carrot Juice      March 2024             3
1517  Store_008      Cranberry Juice       June 2024             6
1215  Store_007     Strawberry Juice      April 2024             4
1092  Store_006  Passion Fruit Juice    January 2024             1
541   Store_003      Blueberry Juice   February 2024             2
120   Store_001          Guava Juice    January 2024             1
171   Store_001      Cranberry Juice      April 2024             4
242   Store_002     Watermelon Juice      March 2024             3
1516  Store_008      Cranberry Juice        May 2024             5
433   Store_003     Watermelon Juice   February 2024             2
676   Store_004         Carrot Juice        May 2024             5
1873  Store_010          Peach Juice   February 2024             2
1371  Store_008          Mango Juice      April 2024             4
255   Store_002     Strawberry Juice      April 2024             4
1515  Store_008      Cranberry Juice      April 2024             4
675   Store_004         Carrot Juice      April 2024             4
828   Store_005     Strawberry Juice    January 2024             1
697   Store_004          Guava Juice   February 2024             2
672   Store_004         Carrot Juice    January 2024             1
1356  Store_008          Apple Juice    January 2024             1
938   Store_005      Cranberry Juice      March 2024             3
684   Store_004    Pomegranate Juice    January 2024             1
695   Store_004    Pomegranate Juice   December 2024            12
459   Store_003          Lemon Juice      April 2024             4
1671  Store_009  Passion Fruit Juice      April 2024             4
136   Store_001  Passion Fruit Juice        May 2024             5
170   Store_001      Cranberry Juice      March 2024             3
1145  Store_006         Papaya Juice       June 2024             6
443   Store_003     Watermelon Juice   December 2024            12
1370  Store_008          Mango Juice      March 2024             3
1115  Store_006          Peach Juice   December 2024            12
1177  Store_007          Mango Juice   February 2024             2
148   Store_001          Peach Juice        May 2024             5
683   Store_004         Carrot Juice   December 2024            12
1490  Store_008          Peach Juice      March 2024             3
845   Store_005          Lemon Juice       June 2024             6
557   Store_003      Cranberry Juice       June 2024             6
1273  Store_007          Guava Juice   February 2024             2
1214  Store_007     Strawberry Juice      March 2024             3
263   Store_002     Strawberry Juice   December 2024            12
481   Store_003         Carrot Juice   February 2024             2
457   Store_003          Lemon Juice   February 2024             2
1368  Store_008          Mango Juice    January 2024             1
257   Store_002     Strawberry Juice       June 2024             6
387   Store_003         Orange Juice      April 2024             4
456   Store_003          Lemon Juice    January 2024             1
1646  Store_009    Pomegranate Juice      March 2024             3
1107  Store_006          Peach Juice      April 2024             4
1358  Store_008          Apple Juice      March 2024             3
256   Store_002     Strawberry Juice        May 2024             5
1512  Store_008      Cranberry Juice    January 2024             1
1213  Store_007     Strawberry Juice   February 2024             2
375   Store_002         Papaya Juice      April 2024             4
341   Store_002          Peach Juice       June 2024             6
544   Store_003      Blueberry Juice        May 2024             5
664   Store_004          Grape Juice        May 2024             5
288   Store_002         Carrot Juice    January 2024             1
1706  Store_009      Cranberry Juice      March 2024             3
384   Store_003         Orange Juice    January 2024             1
388   Store_003         Orange Juice        May 2024             5
339   Store_002          Peach Juice      April 2024             4
700   Store_004          Guava Juice        May 2024             5
1369  Store_008          Mango Juice   February 2024             2
458   Store_003          Lemon Juice      March 2024             3
1877  Store_010          Peach Juice       June 2024             6
1249  Store_007         Carrot Juice   February 2024             2
1191  Store_007      Pineapple Juice      April 2024             4
1669  Store_009  Passion Fruit Juice   February 2024             2
783   Store_005          Apple Juice      April 2024             4
913   Store_005          Peach Juice   February 2024             2
696   Store_004          Guava Juice    January 2024             1
74    Store_001          Lemon Juice      March 2024             3
377   Store_002         Papaya Juice       June 2024             6
299   Store_002         Carrot Juice   December 2024            12
915   Store_005          Peach Juice      April 2024             4
1708  Store_009      Cranberry Juice        May 2024             5
767   Store_004         Papaya Juice   December 2024            12
24    Store_001          Mango Juice    January 2024             1
386   Store_003         Orange Juice      March 2024             3
842   Store_005          Lemon Juice      March 2024             3
134   Store_001  Passion Fruit Juice      March 2024             3
1336  Store_007         Papaya Juice        May 2024             5
434   Store_003     Watermelon Juice      March 2024             3
169   Store_001      Cranberry Juice   February 2024             2
843   Store_005          Lemon Juice      April 2024             4
1360  Store_008          Apple Juice        May 2024             5
1335  Store_007         Papaya Juice      April 2024             4
289   Store_002         Carrot Juice   February 2024             2
1814  Store_010          Grape Juice      March 2024             3
677   Store_004         Carrot Juice       June 2024             6
1204  Store_007     Watermelon Juice        May 2024             5
254   Store_002     Strawberry Juice      March 2024             3
1765  Store_010      Pineapple Juice   February 2024             2
1251  Store_007         Carrot Juice      April 2024             4
844   Store_005          Lemon Juice        May 2024             5
483   Store_003         Carrot Juice      April 2024             4
841   Store_005          Lemon Juice   February 2024             2
1645  Store_009    Pomegranate Juice   February 2024             2
1478  Store_008  Passion Fruit Juice      March 2024             3
1756  Store_010          Mango Juice        May 2024             5
193   Store_002         Orange Juice   February 2024             2
551   Store_003      Blueberry Juice   December 2024            12
832   Store_005     Strawberry Juice        May 2024             5
1275  Store_007          Guava Juice      April 2024             4
840   Store_005          Lemon Juice    January 2024             1
1093  Store_006  Passion Fruit Juice   February 2024             2
132   Store_001  Passion Fruit Juice    January 2024             1
147   Store_001          Peach Juice      April 2024             4
1104  Store_006          Peach Juice    January 2024             1
1876  Store_010          Peach Juice        May 2024             5
1493  Store_008          Peach Juice       June 2024             6
566   Store_003         Papaya Juice      March 2024             3
785   Store_005          Apple Juice       June 2024             6
1216  Store_007     Strawberry Juice        May 2024             5
243   Store_002     Watermelon Juice      April 2024             4
1180  Store_007          Mango Juice        May 2024             5
1143  Store_006         Papaya Juice      April 2024             4
252   Store_002     Strawberry Juice    January 2024             1
790   Store_005          Apple Juice   November 2024            11
829   Store_005     Strawberry Juice   February 2024             2
338   Store_002          Peach Juice      March 2024             3
1190  Store_007      Pineapple Juice      March 2024             3
1176  Store_007          Mango Juice    January 2024             1
410   Store_003          Mango Juice      March 2024             3
1883  Store_010          Peach Juice   December 2024            12
688   Store_004    Pomegranate Juice        May 2024             5
961   Store_006         Orange Juice   February 2024             2
290   Store_002         Carrot Juice      March 2024             3
555   Store_003      Cranberry Juice      April 2024             4
1754  Store_010          Mango Juice      March 2024             3
1768  Store_010      Pineapple Juice        May 2024             5
1200  Store_007     Watermelon Juice    January 2024             1
1333  Store_007         Papaya Juice   February 2024             2
436   Store_003     Watermelon Juice        May 2024             5
1757  Store_010          Mango Juice       June 2024             6
292   Store_002         Carrot Juice        May 2024             5
435   Store_003     Watermelon Juice      April 2024             4
1498  Store_008          Peach Juice   November 2024            11
1250  Store_007         Carrot Juice      March 2024             3
833   Store_005     Strawberry Juice       June 2024             6
1537  Store_009         Orange Juice   February 2024             2
1217  Store_007     Strawberry Juice       June 2024             6
184   Store_001         Papaya Juice        May 2024             5
97    Store_001         Carrot Juice   February 2024             2
1766  Store_010      Pineapple Juice      March 2024             3
850   Store_005          Lemon Juice   November 2024            11
1151  Store_006         Papaya Juice   December 2024            12
1815  Store_010          Grape Juice      April 2024             4
1492  Store_008          Peach Juice        May 2024             5
1672  Store_009  Passion Fruit Juice        May 2024             5
936   Store_005      Cranberry Juice    January 2024             1
293   Store_002         Carrot Juice       June 2024             6
1494  Store_008          Peach Juice       July 2024             7
1274  Store_007          Guava Juice      March 2024             3
760   Store_004         Papaya Juice        May 2024             5
1108  Store_006          Peach Juice        May 2024             5
937   Store_005      Cranberry Juice   February 2024             2
699   Store_004          Guava Juice      April 2024             4
133   Store_001  Passion Fruit Juice   February 2024             2
180   Store_001         Papaya Juice    January 2024             1
786   Store_005          Apple Juice       July 2024             7
1202  Store_007     Watermelon Juice      March 2024             3
460   Store_003          Lemon Juice        May 2024             5
851   Store_005          Lemon Juice   December 2024            12
1644  Store_009    Pomegranate Juice    January 2024             1
144   Store_001          Peach Juice    January 2024             1
761   Store_004         Papaya Juice       June 2024             6
1058  Store_006         Carrot Juice      March 2024             3
941   Store_005      Cranberry Juice       June 2024             6
1286  Store_007  Passion Fruit Juice      March 2024             3
1763  Store_010          Mango Juice   December 2024            12
1707  Store_009      Cranberry Juice      April 2024             4
229   Store_002      Pineapple Juice   February 2024             2
531   Store_003          Peach Juice      April 2024             4
565   Store_003         Papaya Juice   February 2024             2
1872  Store_010          Peach Juice    January 2024             1
917   Store_005          Peach Juice       June 2024             6
1201  Store_007     Watermelon Juice   February 2024             2
484   Store_003         Carrot Juice        May 2024             5
546   Store_003      Blueberry Juice       July 2024             7
1178  Store_007          Mango Juice      March 2024             3
1476  Store_008  Passion Fruit Juice    January 2024             1
1755  Store_010          Mango Juice      April 2024             4
302   Store_002    Pomegranate Juice      March 2024             3
914   Store_005          Peach Juice      March 2024             3
240   Store_002     Watermelon Juice    January 2024             1
539   Store_003          Peach Juice   December 2024            12
960   Store_006         Orange Juice    January 2024             1
378   Store_002         Papaya Juice       July 2024             7
181   Store_001         Papaya Juice   February 2024             2
1287  Store_007  Passion Fruit Juice      April 2024             4
1454  Store_008    Pomegranate Juice      March 2024             3
35    Store_001          Mango Juice   December 2024            12
395   Store_003         Orange Juice   December 2024            12
1359  Store_008          Apple Juice      April 2024             4
182   Store_001         Papaya Juice      March 2024             3
491   Store_003         Carrot Juice   December 2024            12
385   Store_003         Orange Juice   February 2024             2
1538  Store_009         Orange Juice      March 2024             3
1153  Store_007         Orange Juice   February 2024             2
855   Store_005          Grape Juice      April 2024             4
437   Store_003     Watermelon Juice       June 2024             6
194   Store_002         Orange Juice      March 2024             3
1212  Store_007     Strawberry Juice    January 2024             1
461   Store_003          Lemon Juice       June 2024             6
756   Store_004         Papaya Juice    January 2024             1
1118  Store_006      Blueberry Juice      March 2024             3
409   Store_003          Mango Juice   February 2024             2
1539  Store_009         Orange Juice      April 2024             4
545   Store_003      Blueberry Juice       June 2024             6
694   Store_004    Pomegranate Juice   November 2024            11
540   Store_003      Blueberry Juice    January 2024             1
494   Store_003    Pomegranate Juice      March 2024             3
1109  Store_006          Peach Juice       June 2024             6
495   Store_003    Pomegranate Juice      April 2024             4
155   Store_001          Peach Juice   December 2024            12
1146  Store_006         Papaya Juice       July 2024             7
179   Store_001      Cranberry Juice   December 2024            12
830   Store_005     Strawberry Juice      March 2024             3
916   Store_005          Peach Juice        May 2024             5
912   Store_005          Peach Juice    January 2024             1
197   Store_002         Orange Juice       June 2024             6
1277  Store_007          Guava Juice       June 2024             6
123   Store_001          Guava Juice      April 2024             4
846   Store_005          Lemon Juice       July 2024             7
839   Store_005     Strawberry Juice   December 2024            12
1479  Store_008  Passion Fruit Juice      April 2024             4
1252  Store_007         Carrot Juice        May 2024             5
1499  Store_008          Peach Juice   December 2024            12
1357  Store_008          Apple Juice   February 2024             2
1205  Store_007     Watermelon Juice       June 2024             6
145   Store_001          Peach Juice   February 2024             2
940   Store_005      Cranberry Juice        May 2024             5
347   Store_002          Peach Juice   December 2024            12
300   Store_002    Pomegranate Juice    January 2024             1
1034  Store_006          Lemon Juice      March 2024             3
1033  Store_006          Lemon Juice   February 2024             2
1156  Store_007         Orange Juice        May 2024             5
532   Store_003          Peach Juice        May 2024             5

## Top 5 selling During Month

In [11]:
decsending.head(5)

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
374,Store_002,Papaya Juice,March 2024,3,208,5.28,4662,1098.27,5.0,0.70
542,Store_003,Blueberry Juice,March 2024,3,285,5.52,4329,1572.77,4.0,0.72
685,Store_004,Pomegranate Juice,February 2024,2,57,2.77,4314,158.11,3.7,0.97
1489,Store_008,Peach Juice,February 2024,2,123,6.36,4289,782.66,3.4,0.92
782,Store_005,Apple Juice,March 2024,3,193,3.81,4280,735.90,3.9,0.90

## Most-selling during the Month

In [12]:
decsending.loc[[374]]

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
374,Store_002,Papaya Juice,March 2024,3,208,5.28,4662,1098.27,5.0,0.7

## Monthly sales that are greater than or equal 3000

In [13]:
juice2=jusice_dataframe[jusice_dataframe["Monthly_Sales"]>=3000]

In [14]:
juice2

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
24,Store_001,Mango Juice,January 2024,1,94,3.68,3125,346.16,3.2,0.78
26,Store_001,Mango Juice,March 2024,3,280,6.13,3492,1715.65,3.5,0.86
74,Store_001,Lemon Juice,March 2024,3,134,4.39,3131,588.78,3.3,0.77
120,Store_001,Guava Juice,January 2024,1,99,5.91,3470,584.96,4.1,0.82
121,Store_001,Guava Juice,February 2024,2,106,4.86,3863,515.14,4.0,0.77
122,Store_001,Guava Juice,March 2024,3,191,5.32,3858,1015.42,3.4,0.65
132,Store_001,Passion Fruit Juice,January 2024,1,95,3.96,3012,375.92,4.0,0.88
134,Store_001,Passion Fruit Juice,March 2024,3,97,2.74,3118,266.20,3.6,0.92
135,Store_001,Passion Fruit Juice,April 2024,4,229,3.34,3850,764.26,3.7,0.79
136,Store_001,Passion Fruit Juice,May 2024,5,264,4.63,3348,1221.02,4.4,0.62
146,Store_001,Peach Juice,March 2024,3,201,6.09,3611,1223.50,3.2,0.81
147,Store_001,Peach Juice,April 2024,4,85,6.49,3006,551.57,4.8,0.83
148,Store_001,Peach Juice,May 2024,5,128,5.77,3321,738.34,3.5,0.67
169,Store_001,Cranberry Juice,February 2024,2,206,3.42,3112,703.90,4.4,0.89
170,Store_001,Cranberry Juice,March 2024,3,292,4.76,3340,1390.51,4.4,0.84
171,Store_001,Cranberry Juice,April 2024,4,123,3.87,3464,476.02,3.5,0.77
193,Store_002,Orange Juice,February 2024,2,100,5.11,3053,511.10,3.5,0.64
195,Store_002,Orange Juice,April 2024,4,231,3.32,3498,766.91,3.6,0.96
242,Store_002,Watermelon Juice,March 2024,3,276,3.40,3459,937.78,3.4,0.81
243,Store_002,Watermelon Juice,April 2024,4,191,5.94,3000,1134.64,3.9,0.76
253,Store_002,Strawberry Juice,February 2024,2,187,5.78,4227,1080.82,3.5,0.96
254,Store_002,Strawberry Juice,March 2024,3,51,5.83,3089,297.26,4.0,0.60
255,Store_002,Strawberry Juice,April 2024,4,95,3.81,3421,361.54,4.1,0.65
256,Store_002,Strawberry Juice,May 2024,5,241,4.66,3245,1123.05,4.6,0.64
257,Store_002,Strawberry Juice,June 2024,6,123,4.23,3278,520.16,4.7,0.76
263,Store_002,Strawberry Juice,December 2024,12,107,2.50,3290,267.94,3.3,0.79
288,Store_002,Carrot Juice,January 2024,1,74,5.99,3211,443.05,3.4,0.99
289,Store_002,Carrot Juice,February 2024,2,185,5.99,3101,1107.66,3.9,0.62
291,Store_002,Carrot Juice,April 2024,4,180,2.83,3948,508.70,3.8,0.69
299,Store_002,Carrot Juice,December 2024,12,168,4.15,3130,697.56,3.1,0.77
336,Store_002,Peach Juice,January 2024,1,238,3.53,3673,839.25,4.9,0.79
337,Store_002,Peach Juice,February 2024,2,178,3.99,4042,710.94,4.1,0.64
339,Store_002,Peach Juice,April 2024,4,59,3.20,3186,188.75,3.7,0.96
340,Store_002,Peach Juice,May 2024,5,98,3.45,3642,337.85,4.6,0.71
341,Store_002,Peach Juice,June 2024,6,109,5.19,3227,565.24,4.6,0.91
372,Store_002,Papaya Juice,January 2024,1,142,2.57,3637,365.05,4.2,0.75
373,Store_002,Papaya Juice,February 2024,2,54,5.62,3600,303.64,3.9,0.62
374,Store_002,Papaya Juice,March 2024,3,208,5.28,4662,1098.27,5.0,0.70
375,Store_002,Papaya Juice,April 2024,4,122,5.63,3232,686.96,3.5,0.67
376,Store_002,Papaya Juice,May 2024,5,146,4.54,3707,662.50,5.0,0.93
377,Store_002,Papaya Juice,June 2024,6,101,3.20,3131,322.70,4.3,0.94
383,Store_002,Papaya Juice,December 2024,12,213,3.99,3544,848.94,3.5,0.86
384,Store_003,Orange Juice,January 2024,1,232,3.10,3192,718.49,3.3,0.95
386,Store_003,Orange Juice,March 2024,3,70,6.32,3120,442.74,3.3,0.64
387,Store_003,Orange Juice,April 2024,4,218,5.25,3269,1145.05,3.9,0.70
388,Store_003,Orange Juice,May 2024,5,107,3.51,3188,375.81,4.6,0.93
432,Store_003,Watermelon Juice,January 2024,1,139,2.82,3495,392.31,4.5,0.80
433,Store_003,Watermelon Juice,February 2024,2,106,2.53,3448,267.98,3.1,0.69
434,Store_003,Watermelon Juice,March 2024,3,106,5.51,3112,583.58,4.3,0.98
443,Store_003,Watermelon Juice,December 2024,12,177,6.37,3338,1127.39,3.4,0.61
456,Store_003,Lemon Juice,January 2024,1,201,3.93,3267,789.26,4.5,0.71
457,Store_003,Lemon Juice,February 2024,2,186,4.08,3280,759.60,4.8,0.81
458,Store_003,Lemon Juice,March 2024,3,261,4.73,3158,1234.86,3.3,0.85
459,Store_003,Lemon Juice,April 2024,4,76,3.61,3352,274.18,5.0,0.66
481,Store_003,Carrot Juice,February 2024,2,159,6.14,3280,976.75,4.5,0.92
483,Store_003,Carrot Juice,April 2024,4,68,5.99,3068,407.39,3.2,0.88
530,Store_003,Peach Juice,March 2024,3,250,6.44,3645,1609.01,3.6,0.98
541,Store_003,Blueberry Juice,February 2024,2,299,6.28,3471,1876.57,3.3,0.79
542,Store_003,Blueberry Juice,March 2024,3,285,5.52,4329,1572.77,4.0,0.72
543,Store_003,Blueberry Juice,April 2024,4,124,3.31,3506,410.80,4.5,0.75
544,Store_003,Blueberry Juice,May 2024,5,298,3.95,3226,1176.82,4.5,0.96
551,Store_003,Blueberry Juice,December 2024,12,79,6.33,3053,500.05,3.0,1.00
552,Store_003,Cranberry Juice,January 2024,1,281,3.68,3872,1033.65,3.0,0.90
553,Store_003,Cranberry Juice,February 2024,2,50,2.78,4014,138.81,3.0,0.97
554,Store_003,Cranberry Juice,March 2024,3,250,5.56,4124,1391.12,4.7,0.85
557,Store_003,Cranberry Juice,June 2024,6,83,2.52,3314,209.52,3.2,0.95
566,Store_003,Papaya Juice,March 2024,3,57,3.59,3001,204.38,4.0,0.71
661,Store_004,Grape Juice,February 2024,2,128,2.96,3694,379.49,4.6,0.91
662,Store_004,Grape Juice,March 2024,3,197,3.61,3711,711.45,3.6,0.77
663,Store_004,Grape Juice,April 2024,4,267,4.30,4121,1148.22,5.0,0.64
664,Store_004,Grape Juice,May 2024,5,205,4.11,3215,843.45,4.5,0.88
672,Store_004,Carrot Juice,January 2024,1,108,5.45,3380,588.18,4.8,0.68
673,Store_004,Carrot Juice,February 2024,2,147,3.99,3667,587.15,3.1,0.85
674,Store_004,Carrot Juice,March 2024,3,56,3.51,3489,196.69,3.9,0.98
675,Store_004,Carrot Juice,April 2024,4,286,4.97,3400,1421.13,4.5,0.69
676,Store_004,Carrot Juice,May 2024,5,123,2.53,3448,311.59,3.9,0.64
677,Store_004,Carrot Juice,June 2024,6,176,5.73,3092,1008.26,4.7,0.93
683,Store_004,Carrot Juice,December 2024,12,187,6.04,3321,1129.45,3.8,0.80
684,Store_004,Pomegranate Juice,January 2024,1,223,4.09,3354,912.02,4.0,0.70
685,Store_004,Pomegranate Juice,February 2024,2,57,2.77,4314,158.11,3.7,0.97
686,Store_004,Pomegranate Juice,March 2024,3,138,3.83,3851,529.15,4.7,0.97
687,Store_004,Pomegranate Juice,April 2024,4,131,5.65,4130,740.09,3.9,0.85
695,Store_004,Pomegranate Juice,December 2024,12,76,4.56,3352,346.56,4.1,0.74
696,Store_004,Guava Juice,January 2024,1,202,5.81,3139,1174.12,3.4,0.92
697,Store_004,Guava Juice,February 2024,2,159,3.92,3388,622.91,4.0,0.98
698,Store_004,Guava Juice,March 2024,3,262,6.11,3609,1601.93,3.2,0.93
700,Store_004,Guava Juice,May 2024,5,244,4.16,3173,1014.57,3.0,0.72
757,Store_004,Papaya Juice,February 2024,2,227,2.58,4071,584.88,4.6,0.84
758,Store_004,Papaya Juice,March 2024,3,61,4.32,3846,263.49,4.4,0.96
759,Store_004,Papaya Juice,April 2024,4,139,4.11,3643,570.95,3.3,0.83
767,Store_004,Papaya Juice,December 2024,12,143,3.72,3126,532.56,4.1,0.92
780,Store_005,Apple Juice,January 2024,1,267,3.28,3976,875.94,4.0,0.90
781,Store_005,Apple Juice,February 2024,2,221,5.25,3692,1159.84,4.3,0.65
782,Store_005,Apple Juice,March 2024,3,193,3.81,4280,735.90,3.9,0.90
783,Store_005,Apple Juice,April 2024,4,190,6.06,3149,1151.31,4.6,0.80
784,Store_005,Apple Juice,May 2024,5,237,4.46,3700,1056.66,4.3,0.69
785,Store_005,Apple Juice,June 2024,6,74,5.47,3001,404.51,3.6,0.65
828,Store_005,Strawberry Juice,January 2024,1,157,2.91,3394,457.35,3.3,0.83
832,Store_005,Strawberry Juice,May 2024,5,298,4.81,3051,1433.54,3.7,0.93
840,Store_005,Lemon Juice,January 2024,1,192,4.95,3018,950.63,4.9,0.86
841,Store_005,Lemon Juice,February 2024,2,196,3.43,3067,671.48,4.4,0.98
842,Store_005,Lemon Juice,March 2024,3,201,4.95,3119,994.41,3.7,0.70
843,Store_005,Lemon Juice,April 2024,4,81,5.50,3110,445.51,4.1,0.82
844,Store_005,Lemon Juice,May 2024,5,256,4.08,3071,1044.75,3.4,0.66
845,Store_005,Lemon Juice,June 2024,6,239,3.13,3314,746.91,3.4,0.81
913,Store_005,Peach Juice,February 2024,2,212,5.17,3146,1095.29,3.2,0.83
915,Store_005,Peach Juice,April 2024,4,190,5.19,3130,987.01,4.5,0.72
938,Store_005,Cranberry Juice,March 2024,3,88,6.26,3356,550.73,4.5,0.83
939,Store_005,Cranberry Juice,April 2024,4,207,3.76,3519,778.33,4.6,0.97
1092,Store_006,Passion Fruit Juice,January 2024,1,156,2.84,3473,442.58,3.7,0.87
1093,Store_006,Passion Fruit Juice,February 2024,2,180,3.16,3015,569.16,4.4,0.81
1094,Store_006,Passion Fruit Juice,March 2024,3,142,3.65,3605,517.72,4.0,0.90
1095,Store_006,Passion Fruit Juice,April 2024,4,215,5.93,3760,1275.32,4.3,0.77
1096,Store_006,Passion Fruit Juice,May 2024,5,63,5.28,3574,332.94,3.4,0.64
1104,Store_006,Peach Juice,January 2024,1,216,6.07,3004,1311.90,3.8,0.72
1105,Store_006,Peach Juice,February 2024,2,87,2.65,3821,230.28,3.9,0.73
1106,Store_006,Peach Juice,March 2024,3,171,2.70,4226,461.47,4.2,0.63
1107,Store_006,Peach Juice,April 2024,4,169,6.39,3260,1079.88,4.0,0.85
1115,Store_006,Peach Juice,December 2024,12,243,6.38,3332,1550.41,4.7,0.84
1140,Store_006,Papaya Juice,January 2024,1,137,4.83,3960,662.15,4.8,0.66
1141,Store_006,Papaya Juice,February 2024,2,87,5.68,3816,494.39,3.2,0.71
1142,Store_006,Papaya Juice,March 2024,3,264,2.53,3918,667.76,4.4,0.86
1144,Store_006,Papaya Juice,May 2024,5,226,5.37,3830,1213.40,4.2,0.92
1145,Store_006,Papaya Juice,June 2024,6,245,6.26,3339,1532.60,3.6,0.79
1177,Store_007,Mango Juice,February 2024,2,211,3.99,3324,841.50,3.2,0.78
1191,Store_007,Pineapple Juice,April 2024,4,236,4.17,3152,984.92,3.9,0.72
1204,Store_007,Watermelon Juice,May 2024,5,138,4.25,3092,587.13,3.1,0.80
1213,Store_007,Strawberry Juice,February 2024,2,228,4.25,3236,968.32,3.9,0.92
1214,Store_007,Strawberry Juice,March 2024,3,60,2.60,3294,155.91,4.4,0.89
1215,Store_007,Strawberry Juice,April 2024,4,272,3.89,3478,1058.39,3.0,0.64
1216,Store_007,Strawberry Juice,May 2024,5,172,5.09,3001,875.37,3.3,0.86
1249,Store_007,Carrot Juice,February 2024,2,265,5.07,3154,1344.53,3.4,0.64
1251,Store_007,Carrot Juice,April 2024,4,115,5.21,3079,598.98,4.4,0.85
1273,Store_007,Guava Juice,February 2024,2,247,5.69,3299,1404.33,4.2,0.95
1275,Store_007,Guava Juice,April 2024,4,229,2.57,3031,587.77,4.7,0.69
1335,Store_007,Papaya Juice,April 2024,4,135,2.71,3106,365.59,3.2,0.60
1336,Store_007,Papaya Juice,May 2024,5,80,5.96,3116,476.89,4.2,0.89
1356,Store_008,Apple Juice,January 2024,1,98,3.57,3376,350.03,4.0,0.83
1358,Store_008,Apple Juice,March 2024,3,269,2.69,3257,723.31,3.4,0.98
1360,Store_008,Apple Juice,May 2024,5,272,4.04,3109,1097.54,4.9,0.66
1368,Store_008,Mango Juice,January 2024,1,172,3.90,3279,670.80,4.9,0.63
1369,Store_008,Mango Juice,February 2024,2,275,6.35,3159,1745.27,4.6,0.85
1370,Store_008,Mango Juice,March 2024,3,55,3.28,3333,180.39,4.7,0.83
1371,Store_008,Mango Juice,April 2024,4,284,4.04,3422,1146.16,3.9,0.66
1477,Store_008,Passion Fruit Juice,February 2024,2,213,4.94,3511,1052.84,3.5,0.71
1478,Store_008,Passion Fruit Juice,March 2024,3,245,5.04,3058,1235.88,3.3,0.77
1488,Store_008,Peach Juice,January 2024,1,74,4.89,3916,361.89,4.6,0.92
1489,Store_008,Peach Juice,February 2024,2,123,6.36,4289,782.66,3.4,0.92
1490,Store_008,Peach Juice,March 2024,3,155,3.00,3316,464.65,4.9,0.72
1491,Store_008,Peach Juice,April 2024,4,64,4.55,4173,290.95,4.8,0.96
1493,Store_008,Peach Juice,June 2024,6,131,3.17,3002,414.98,3.2,0.63
1512,Store_008,Cranberry Juice,January 2024,1,125,3.63,3236,453.40,4.4,0.94
1513,Store_008,Cranberry Juice,February 2024,2,88,4.21,3916,370.34,3.3,0.98
1514,Store_008,Cranberry Juice,March 2024,3,235,4.78,3768,1122.67,3.8,0.90
1515,Store_008,Cranberry Juice,April 2024,4,250,5.97,3401,1492.15,4.3,0.62
1516,Store_008,Cranberry Juice,May 2024,5,194,6.03,3456,1169.61,3.3,0.88
1517,Store_008,Cranberry Juice,June 2024,6,193,5.51,3482,1063.61,3.9,0.78
1645,Store_009,Pomegranate Juice,February 2024,2,261,5.81,3066,1515.62,4.7,0.72
1646,Store_009,Pomegranate Juice,March 2024,3,68,4.86,3261,330.73,5.0,0.67
1669,Store_009,Passion Fruit Juice,February 2024,2,167,3.30,3150,551.20,3.6,0.84
1671,Store_009,Passion Fruit Juice,April 2024,4,61,5.37,3350,327.28,4.3,0.79
1706,Store_009,Cranberry Juice,March 2024,3,179,6.26,3205,1120.92,4.8,0.83
1708,Store_009,Cranberry Juice,May 2024,5,125,6.28,3129,784.55,3.7,0.82
1752,Store_010,Mango Juice,January 2024,1,110,5.61,3521,616.69,4.6,0.62
1753,Store_010,Mango Juice,February 2024,2,292,3.48,3564,1016.90,3.2,0.92
1756,Store_010,Mango Juice,May 2024,5,111,5.72,3054,635.27,3.5,0.79
1765,Store_010,Pineapple Juice,February 2024,2,129,6.04,3086,778.77,4.7,0.78
1814,Store_010,Grape Juice,March 2024,3,116,4.08,3096,473.63,3.6,0.95
1873,Store_010,Peach Juice,February 2024,2,112,3.05,3425,341.78,4.6,0.92
1874,Store_010,Peach Juice,March 2024,3,52,5.89,3641,306.25,3.0,0.76
1875,Store_010,Peach Juice,April 2024,4,236,2.53,4042,598.18,4.9,0.63
1876,Store_010,Peach Juice,May 2024,5,114,5.12,3003,583.85,3.8,0.89
1877,Store_010,Peach Juice,June 2024,6,59,6.02,3157,355.04,4.0,0.85

## Reorder Rate for juice sales that are grater than 0.6

In [15]:
juice3=jusice_dataframe[jusice_dataframe["Reorder_Rate"]>0.6]

In [16]:
juice3

       Store_ID           Juice_Type           Month  Month_Number  \
0     Store_001         Orange Juice    January 2024             1
1     Store_001         Orange Juice   February 2024             2
2     Store_001         Orange Juice      March 2024             3
3     Store_001         Orange Juice      April 2024             4
4     Store_001         Orange Juice        May 2024             5
5     Store_001         Orange Juice       June 2024             6
6     Store_001         Orange Juice       July 2024             7
7     Store_001         Orange Juice     August 2024             8
8     Store_001         Orange Juice  September 2024             9
9     Store_001         Orange Juice    October 2024            10
10    Store_001         Orange Juice   November 2024            11
11    Store_001         Orange Juice   December 2024            12
12    Store_001          Apple Juice    January 2024             1
13    Store_001          Apple Juice   February 2024             2
14    Store_001          Apple Juice      March 2024             3
15    Store_001          Apple Juice      April 2024             4
16    Store_001          Apple Juice        May 2024             5
17    Store_001          Apple Juice       June 2024             6
18    Store_001          Apple Juice       July 2024             7
19    Store_001          Apple Juice     August 2024             8
20    Store_001          Apple Juice  September 2024             9
21    Store_001          Apple Juice    October 2024            10
22    Store_001          Apple Juice   November 2024            11
23    Store_001          Apple Juice   December 2024            12
24    Store_001          Mango Juice    January 2024             1
25    Store_001          Mango Juice   February 2024             2
26    Store_001          Mango Juice      March 2024             3
27    Store_001          Mango Juice      April 2024             4
28    Store_001          Mango Juice        May 2024             5
29    Store_001          Mango Juice       June 2024             6
30    Store_001          Mango Juice       July 2024             7
31    Store_001          Mango Juice     August 2024             8
32    Store_001          Mango Juice  September 2024             9
33    Store_001          Mango Juice    October 2024            10
34    Store_001          Mango Juice   November 2024            11
35    Store_001          Mango Juice   December 2024            12
36    Store_001      Pineapple Juice    January 2024             1
37    Store_001      Pineapple Juice   February 2024             2
38    Store_001      Pineapple Juice      March 2024             3
39    Store_001      Pineapple Juice      April 2024             4
40    Store_001      Pineapple Juice        May 2024             5
41    Store_001      Pineapple Juice       June 2024             6
42    Store_001      Pineapple Juice       July 2024             7
43    Store_001      Pineapple Juice     August 2024             8
44    Store_001      Pineapple Juice  September 2024             9
45    Store_001      Pineapple Juice    October 2024            10
46    Store_001      Pineapple Juice   November 2024            11
47    Store_001      Pineapple Juice   December 2024            12
48    Store_001     Watermelon Juice    January 2024             1
49    Store_001     Watermelon Juice   February 2024             2
50    Store_001     Watermelon Juice      March 2024             3
51    Store_001     Watermelon Juice      April 2024             4
52    Store_001     Watermelon Juice        May 2024             5
53    Store_001     Watermelon Juice       June 2024             6
54    Store_001     Watermelon Juice       July 2024             7
55    Store_001     Watermelon Juice     August 2024             8
56    Store_001     Watermelon Juice  September 2024             9
57    Store_001     Watermelon Juice    October 2024            10
58    Store_001     Watermelon Juice   November 2024            11
59    Store_001     Watermelon Juice   December 2024            12
60    Store_001     Strawberry Juice    January 2024             1
61    Store_001     Strawberry Juice   February 2024             2
62    Store_001     Strawberry Juice      March 2024             3
63    Store_001     Strawberry Juice      April 2024             4
64    Store_001     Strawberry Juice        May 2024             5
65    Store_001     Strawberry Juice       June 2024             6
66    Store_001     Strawberry Juice       July 2024             7
67    Store_001     Strawberry Juice     August 2024             8
68    Store_001     Strawberry Juice  September 2024             9
69    Store_001     Strawberry Juice    October 2024            10
70    Store_001     Strawberry Juice   November 2024            11
71    Store_001     Strawberry Juice   December 2024            12
72    Store_001          Lemon Juice    January 2024             1
73    Store_001          Lemon Juice   February 2024             2
74    Store_001          Lemon Juice      March 2024             3
75    Store_001          Lemon Juice      April 2024             4
76    Store_001          Lemon Juice        May 2024             5
77    Store_001          Lemon Juice       June 2024             6
78    Store_001          Lemon Juice       July 2024             7
79    Store_001          Lemon Juice     August 2024             8
80    Store_001          Lemon Juice  September 2024             9
81    Store_001          Lemon Juice    October 2024            10
82    Store_001          Lemon Juice   November 2024            11
83    Store_001          Lemon Juice   December 2024            12
84    Store_001          Grape Juice    January 2024             1
85    Store_001          Grape Juice   February 2024             2
86    Store_001          Grape Juice      March 2024             3
87    Store_001          Grape Juice      April 2024             4
88    Store_001          Grape Juice        May 2024             5
89    Store_001          Grape Juice       June 2024             6
90    Store_001          Grape Juice       July 2024             7
91    Store_001          Grape Juice     August 2024             8
92    Store_001          Grape Juice  September 2024             9
93    Store_001          Grape Juice    October 2024            10
94    Store_001          Grape Juice   November 2024            11
95    Store_001          Grape Juice   December 2024            12
96    Store_001         Carrot Juice    January 2024             1
97    Store_001         Carrot Juice   February 2024             2
98    Store_001         Carrot Juice      March 2024             3
99    Store_001         Carrot Juice      April 2024             4
100   Store_001         Carrot Juice        May 2024             5
101   Store_001         Carrot Juice       June 2024             6
102   Store_001         Carrot Juice       July 2024             7
103   Store_001         Carrot Juice     August 2024             8
104   Store_001         Carrot Juice  September 2024             9
105   Store_001         Carrot Juice    October 2024            10
106   Store_001         Carrot Juice   November 2024            11
107   Store_001         Carrot Juice   December 2024            12
108   Store_001    Pomegranate Juice    January 2024             1
109   Store_001    Pomegranate Juice   February 2024             2
110   Store_001    Pomegranate Juice      March 2024             3
111   Store_001    Pomegranate Juice      April 2024             4
112   Store_001    Pomegranate Juice        May 2024             5
113   Store_001    Pomegranate Juice       June 2024             6
114   Store_001    Pomegranate Juice       July 2024             7
115   Store_001    Pomegranate Juice     August 2024             8
116   Store_001    Pomegranate Juice  September 2024             9
117   Store_001    Pomegranate Juice    October 2024            10
118   Store_001    Pomegranate Juice   November 2024            11
119   Store_001    Pomegranate Juice   December 2024            12
120   Store_001          Guava Juice    January 2024             1
121   Store_001          Guava Juice   February 2024             2
122   Store_001          Guava Juice      March 2024             3
123   Store_001          Guava Juice      April 2024             4
124   Store_001          Guava Juice        May 2024             5
125   Store_001          Guava Juice       June 2024             6
126   Store_001          Guava Juice       July 2024             7
127   Store_001          Guava Juice     August 2024             8
128   Store_001          Guava Juice  September 2024             9
129   Store_001          Guava Juice    October 2024            10
130   Store_001          Guava Juice   November 2024            11
131   Store_001          Guava Juice   December 2024            12
132   Store_001  Passion Fruit Juice    January 2024             1
133   Store_001  Passion Fruit Juice   February 2024             2
134   Store_001  Passion Fruit Juice      March 2024             3
135   Store_001  Passion Fruit Juice      April 2024             4
136   Store_001  Passion Fruit Juice        May 2024             5
137   Store_001  Passion Fruit Juice       June 2024             6
138   Store_001  Passion Fruit Juice       July 2024             7
139   Store_001  Passion Fruit Juice     August 2024             8
140   Store_001  Passion Fruit Juice  September 2024             9
141   Store_001  Passion Fruit Juice    October 2024            10
142   Store_001  Passion Fruit Juice   November 2024            11
143   Store_001  Passion Fruit Juice   December 2024            12
144   Store_001          Peach Juice    January 2024             1
145   Store_001          Peach Juice   February 2024             2
146   Store_001          Peach Juice      March 2024             3
147   Store_001          Peach Juice      April 2024             4
148   Store_001          Peach Juice        May 2024             5
149   Store_001          Peach Juice       June 2024             6
150   Store_001          Peach Juice       July 2024             7
151   Store_001          Peach Juice     August 2024             8
152   Store_001          Peach Juice  September 2024             9
153   Store_001          Peach Juice    October 2024            10
154   Store_001          Peach Juice   November 2024            11
155   Store_001          Peach Juice   December 2024            12
156   Store_001      Blueberry Juice    January 2024             1
157   Store_001      Blueberry Juice   February 2024             2
158   Store_001      Blueberry Juice      March 2024             3
159   Store_001      Blueberry Juice      April 2024             4
160   Store_001      Blueberry Juice        May 2024             5
161   Store_001      Blueberry Juice       June 2024             6
162   Store_001      Blueberry Juice       July 2024             7
163   Store_001      Blueberry Juice     August 2024             8
164   Store_001      Blueberry Juice  September 2024             9
165   Store_001      Blueberry Juice    October 2024            10
166   Store_001      Blueberry Juice   November 2024            11
167   Store_001      Blueberry Juice   December 2024            12
168   Store_001      Cranberry Juice    January 2024             1
169   Store_001      Cranberry Juice   February 2024             2
170   Store_001      Cranberry Juice      March 2024             3
171   Store_001      Cranberry Juice      April 2024             4
172   Store_001      Cranberry Juice        May 2024             5
173   Store_001      Cranberry Juice       June 2024             6
174   Store_001      Cranberry Juice       July 2024             7
175   Store_001      Cranberry Juice     August 2024             8
176   Store_001      Cranberry Juice  September 2024             9
177   Store_001      Cranberry Juice    October 2024            10
178   Store_001      Cranberry Juice   November 2024            11
179   Store_001      Cranberry Juice   December 2024            12
180   Store_001         Papaya Juice    January 2024             1
181   Store_001         Papaya Juice   February 2024             2
182   Store_001         Papaya Juice      March 2024             3
183   Store_001         Papaya Juice      April 2024             4
184   Store_001         Papaya Juice        May 2024             5
185   Store_001         Papaya Juice       June 2024             6
186   Store_001         Papaya Juice       July 2024             7
187   Store_001         Papaya Juice     August 2024             8
188   Store_001         Papaya Juice  September 2024             9
189   Store_001         Papaya Juice    October 2024            10
190   Store_001         Papaya Juice   November 2024            11
191   Store_001         Papaya Juice   December 2024            12
192   Store_002         Orange Juice    January 2024             1
193   Store_002         Orange Juice   February 2024             2
194   Store_002         Orange Juice      March 2024             3
195   Store_002         Orange Juice      April 2024             4
196   Store_002         Orange Juice        May 2024             5
197   Store_002         Orange Juice       June 2024             6
198   Store_002         Orange Juice       July 2024             7
199   Store_002         Orange Juice     August 2024             8
200   Store_002         Orange Juice  September 2024             9
201   Store_002         Orange Juice    October 2024            10
202   Store_002         Orange Juice   November 2024            11
203   Store_002         Orange Juice   December 2024            12
204   Store_002          Apple Juice    January 2024             1
205   Store_002          Apple Juice   February 2024             2
206   Store_002          Apple Juice      March 2024             3
207   Store_002          Apple Juice      April 2024             4
208   Store_002          Apple Juice        May 2024             5
209   Store_002          Apple Juice       June 2024             6
210   Store_002          Apple Juice       July 2024             7
211   Store_002          Apple Juice     August 2024             8
212   Store_002          Apple Juice  September 2024             9
213   Store_002          Apple Juice    October 2024            10
214   Store_002          Apple Juice   November 2024            11
215   Store_002          Apple Juice   December 2024            12
216   Store_002          Mango Juice    January 2024             1
217   Store_002          Mango Juice   February 2024             2
218   Store_002          Mango Juice      March 2024             3
219   Store_002          Mango Juice      April 2024             4
220   Store_002          Mango Juice        May 2024             5
221   Store_002          Mango Juice       June 2024             6
222   Store_002          Mango Juice       July 2024             7
223   Store_002          Mango Juice     August 2024             8
224   Store_002          Mango Juice  September 2024             9
225   Store_002          Mango Juice    October 2024            10
226   Store_002          Mango Juice   November 2024            11
227   Store_002          Mango Juice   December 2024            12
228   Store_002      Pineapple Juice    January 2024             1
229   Store_002      Pineapple Juice   February 2024             2
230   Store_002      Pineapple Juice      March 2024             3
231   Store_002      Pineapple Juice      April 2024             4
232   Store_002      Pineapple Juice        May 2024             5
233   Store_002      Pineapple Juice       June 2024             6
234   Store_002      Pineapple Juice       July 2024             7
235   Store_002      Pineapple Juice     August 2024             8
236   Store_002      Pineapple Juice  September 2024             9
237   Store_002      Pineapple Juice    October 2024            10
238   Store_002      Pineapple Juice   November 2024            11
239   Store_002      Pineapple Juice   December 2024            12
240   Store_002     Watermelon Juice    January 2024             1
241   Store_002     Watermelon Juice   February 2024             2
242   Store_002     Watermelon Juice      March 2024             3
243   Store_002     Watermelon Juice      April 2024             4
244   Store_002     Watermelon Juice        May 2024             5
245   Store_002     Watermelon Juice       June 2024             6
246   Store_002     Watermelon Juice       July 2024             7
247   Store_002     Watermelon Juice     August 2024             8
248   Store_002     Watermelon Juice  September 2024             9
249   Store_002     Watermelon Juice    October 2024            10
250   Store_002     Watermelon Juice   November 2024            11
251   Store_002     Watermelon Juice   December 2024            12
252   Store_002     Strawberry Juice    January 2024             1
253   Store_002     Strawberry Juice   February 2024             2
255   Store_002     Strawberry Juice      April 2024             4
256   Store_002     Strawberry Juice        May 2024             5
257   Store_002     Strawberry Juice       June 2024             6
258   Store_002     Strawberry Juice       July 2024             7
259   Store_002     Strawberry Juice     August 2024             8
260   Store_002     Strawberry Juice  September 2024             9
261   Store_002     Strawberry Juice    October 2024            10
262   Store_002     Strawberry Juice   November 2024            11
263   Store_002     Strawberry Juice   December 2024            12
264   Store_002          Lemon Juice    January 2024             1
265   Store_002          Lemon Juice   February 2024             2
266   Store_002          Lemon Juice      March 2024             3
267   Store_002          Lemon Juice      April 2024             4
268   Store_002          Lemon Juice        May 2024             5
269   Store_002          Lemon Juice       June 2024             6
270   Store_002          Lemon Juice       July 2024             7
271   Store_002          Lemon Juice     August 2024             8
272   Store_002          Lemon Juice  September 2024             9
273   Store_002          Lemon Juice    October 2024            10
274   Store_002          Lemon Juice   November 2024            11
275   Store_002          Lemon Juice   December 2024            12
276   Store_002          Grape Juice    January 2024             1
277   Store_002          Grape Juice   February 2024             2
278   Store_002          Grape Juice      March 2024             3
279   Store_002          Grape Juice      April 2024             4
280   Store_002          Grape Juice        May 2024             5
281   Store_002          Grape Juice       June 2024             6
282   Store_002          Grape Juice       July 2024             7
283   Store_002          Grape Juice     August 2024             8
284   Store_002          Grape Juice  September 2024             9
285   Store_002          Grape Juice    October 2024            10
286   Store_002          Grape Juice   November 2024            11
287   Store_002          Grape Juice   December 2024            12
288   Store_002         Carrot Juice    January 2024             1
289   Store_002         Carrot Juice   February 2024             2
290   Store_002         Carrot Juice      March 2024             3
291   Store_002         Carrot Juice      April 2024             4
292   Store_002         Carrot Juice        May 2024             5
293   Store_002         Carrot Juice       June 2024             6
294   Store_002         Carrot Juice       July 2024             7
295   Store_002         Carrot Juice     August 2024             8
296   Store_002         Carrot Juice  September 2024             9
297   Store_002         Carrot Juice    October 2024            10

## Analyizing Market Performance :Reorder_Rate for "Orange Juice" And "Mango Juice" that are grater or equal 0.6

In [21]:
juice4=jusice_dataframe[(jusice_dataframe["Juice_Type"]=="Mango Juice")&(jusice_dataframe["Reorder_Rate"]>=0.6)|(jusice_dataframe["Juice_Type"]=="Orange Juice")&(jusice_dataframe["Reorder_Rate"]>=0.6)]

In [22]:
juice4

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
0,Store_001,Orange Juice,January 2024,1,121,4.89,1365,592.25,3.3,0.66
1,Store_001,Orange Juice,February 2024,2,137,3.83,1410,525.37,3.3,0.86
2,Store_001,Orange Juice,March 2024,3,137,5.83,1454,798.68,3.4,0.67
3,Store_001,Orange Juice,April 2024,4,253,4.95,1496,1251.49,3.0,0.61
4,Store_001,Orange Juice,May 2024,5,219,2.69,1579,588.38,4.9,0.69
5,Store_001,Orange Juice,June 2024,6,239,3.30,1137,788.39,4.0,0.84
6,Store_001,Orange Juice,July 2024,7,100,5.22,946,522.12,3.9,0.61
7,Store_001,Orange Juice,August 2024,8,63,5.73,1184,361.22,3.6,0.64
8,Store_001,Orange Juice,September 2024,9,160,5.23,1022,837.29,4.2,0.93
9,Store_001,Orange Juice,October 2024,10,130,3.54,875,459.57,4.3,0.72
10,Store_001,Orange Juice,November 2024,11,155,4.77,1165,739.47,3.1,0.94
11,Store_001,Orange Juice,December 2024,12,251,6.08,1332,1525.91,4.2,0.97
24,Store_001,Mango Juice,January 2024,1,94,3.68,3125,346.16,3.2,0.78
25,Store_001,Mango Juice,February 2024,2,133,6.07,2592,807.34,4.1,0.92
26,Store_001,Mango Juice,March 2024,3,280,6.13,3492,1715.65,3.5,0.86
27,Store_001,Mango Juice,April 2024,4,254,5.94,2337,1509.50,3.0,0.80
28,Store_001,Mango Juice,May 2024,5,214,5.27,2578,1127.73,3.5,0.70
29,Store_001,Mango Juice,June 2024,6,209,4.58,2011,956.21,4.4,0.75
30,Store_001,Mango Juice,July 2024,7,101,3.49,2343,352.24,4.4,0.88
31,Store_001,Mango Juice,August 2024,8,233,2.65,1474,616.88,4.2,0.80
32,Store_001,Mango Juice,September 2024,9,278,3.88,1332,1078.72,4.3,0.87
33,Store_001,Mango Juice,October 2024,10,267,6.44,1737,1720.17,3.5,0.87
34,Store_001,Mango Juice,November 2024,11,172,3.47,2177,596.61,4.6,0.79
35,Store_001,Mango Juice,December 2024,12,263,4.64,2767,1221.13,3.2,0.93
192,Store_002,Orange Juice,January 2024,1,236,4.52,2420,1067.20,4.2,0.74
193,Store_002,Orange Juice,February 2024,2,100,5.11,3053,511.10,3.5,0.64
194,Store_002,Orange Juice,March 2024,3,127,4.91,2750,623.92,4.6,0.99
195,Store_002,Orange Juice,April 2024,4,231,3.32,3498,766.91,3.6,0.96
196,Store_002,Orange Juice,May 2024,5,56,5.44,2183,304.84,4.7,0.65
197,Store_002,Orange Juice,June 2024,6,78,4.19,2713,326.48,4.8,0.93
198,Store_002,Orange Juice,July 2024,7,283,5.80,1877,1641.52,3.7,0.61
199,Store_002,Orange Juice,August 2024,8,86,4.14,1976,355.84,4.1,0.77
200,Store_002,Orange Juice,September 2024,9,293,6.40,1514,1874.67,4.6,0.65
201,Store_002,Orange Juice,October 2024,10,108,6.08,1791,656.45,4.6,0.77
202,Store_002,Orange Juice,November 2024,11,63,5.47,1621,344.41,4.4,0.76
203,Store_002,Orange Juice,December 2024,12,71,5.84,2092,414.62,5.0,0.81
216,Store_002,Mango Juice,January 2024,1,228,3.59,1613,818.20,4.2,0.74
217,Store_002,Mango Juice,February 2024,2,98,3.05,1846,298.63,4.9,0.78
218,Store_002,Mango Juice,March 2024,3,111,6.33,1990,702.93,4.5,0.86
219,Store_002,Mango Juice,April 2024,4,278,5.27,2435,1464.81,4.7,0.70
220,Store_002,Mango Juice,May 2024,5,192,5.27,2006,1012.36,3.1,0.87
221,Store_002,Mango Juice,June 2024,6,65,6.20,1432,403.06,3.4,0.83
222,Store_002,Mango Juice,July 2024,7,63,2.98,1736,187.87,4.5,0.68
223,Store_002,Mango Juice,August 2024,8,108,6.28,1097,677.92,3.9,0.94
224,Store_002,Mango Juice,September 2024,9,195,4.59,1395,895.00,4.3,0.86
225,Store_002,Mango Juice,October 2024,10,157,2.98,1226,468.22,3.2,0.88
226,Store_002,Mango Juice,November 2024,11,232,4.12,1393,955.36,4.1,0.92
227,Store_002,Mango Juice,December 2024,12,263,3.78,1778,992.83,4.3,0.95
384,Store_003,Orange Juice,January 2024,1,232,3.10,3192,718.49,3.3,0.95
385,Store_003,Orange Juice,February 2024,2,131,4.40,2758,576.93,3.8,0.76
386,Store_003,Orange Juice,March 2024,3,70,6.32,3120,442.74,3.3,0.64
387,Store_003,Orange Juice,April 2024,4,218,5.25,3269,1145.05,3.9,0.70
388,Store_003,Orange Juice,May 2024,5,107,3.51,3188,375.81,4.6,0.93
389,Store_003,Orange Juice,June 2024,6,57,6.08,2435,346.59,4.3,0.85
390,Store_003,Orange Juice,July 2024,7,137,6.03,1714,826.09,3.2,1.00
391,Store_003,Orange Juice,August 2024,8,57,2.67,1765,152.00,3.2,0.89
392,Store_003,Orange Juice,September 2024,9,201,2.92,1415,587.22,3.1,0.80
393,Store_003,Orange Juice,October 2024,10,208,3.69,1724,766.72,3.7,0.91
394,Store_003,Orange Juice,November 2024,11,77,3.92,2207,301.79,3.8,0.82
395,Store_003,Orange Juice,December 2024,12,57,3.56,2762,202.93,3.0,0.63
408,Store_003,Mango Juice,January 2024,1,137,3.87,2289,530.13,3.8,0.90
409,Store_003,Mango Juice,February 2024,2,52,3.69,2745,191.89,4.1,0.88
410,Store_003,Mango Juice,March 2024,3,160,6.01,2967,961.37,3.9,0.66
411,Store_003,Mango Juice,April 2024,4,121,3.49,2560,421.89,4.5,1.00
412,Store_003,Mango Juice,May 2024,5,273,6.02,1917,1643.26,4.3,0.72
413,Store_003,Mango Juice,June 2024,6,95,4.96,2178,471.57,3.4,0.74
414,Store_003,Mango Juice,July 2024,7,293,4.60,1879,1346.81,4.7,0.94
415,Store_003,Mango Juice,August 2024,8,255,3.31,1665,844.03,4.9,0.75
416,Store_003,Mango Juice,September 2024,9,292,5.87,1293,1713.42,3.9,0.80
417,Store_003,Mango Juice,October 2024,10,160,4.29,1249,687.11,4.4,0.95
418,Store_003,Mango Juice,November 2024,11,86,5.15,1750,443.09,3.0,0.67
419,Store_003,Mango Juice,December 2024,12,223,3.92,1611,874.60,4.6,0.64
576,Store_004,Orange Juice,January 2024,1,70,4.40,1365,308.11,4.3,1.00
577,Store_004,Orange Juice,February 2024,2,295,6.33,1370,1866.52,4.0,0.77
578,Store_004,Orange Juice,March 2024,3,195,5.04,1651,982.35,4.5,0.60
579,Store_004,Orange Juice,April 2024,4,62,4.17,1861,258.29,4.6,0.94
580,Store_004,Orange Juice,May 2024,5,122,5.98,1314,729.44,4.5,0.86
581,Store_004,Orange Juice,June 2024,6,136,4.93,1445,670.62,3.6,0.65
582,Store_004,Orange Juice,July 2024,7,67,5.45,1164,365.04,4.9,0.62
583,Store_004,Orange Juice,August 2024,8,103,3.30,1026,339.58,4.8,0.71
584,Store_004,Orange Juice,September 2024,9,106,5.79,856,614.08,4.6,0.82
585,Store_004,Orange Juice,October 2024,10,123,2.56,803,314.73,3.8,0.73
586,Store_004,Orange Juice,November 2024,11,149,6.30,887,938.01,3.1,0.89
587,Store_004,Orange Juice,December 2024,12,61,4.88,1204,297.71,3.0,0.79
600,Store_004,Mango Juice,January 2024,1,205,5.07,1747,1039.61,4.6,0.98
601,Store_004,Mango Juice,February 2024,2,231,4.38,1873,1011.77,4.8,0.88
602,Store_004,Mango Juice,March 2024,3,290,6.22,1706,1804.50,4.0,0.69
603,Store_004,Mango Juice,April 2024,4,210,6.33,1639,1329.66,4.1,0.70
604,Store_004,Mango Juice,May 2024,5,70,6.35,1830,444.45,4.2,0.97
605,Store_004,Mango Juice,June 2024,6,127,4.69,1757,595.16,3.9,0.62
606,Store_004,Mango Juice,July 2024,7,142,4.43,1171,628.40,4.8,0.87
607,Store_004,Mango Juice,August 2024,8,124,5.67,1006,703.40,4.7,0.70
608,Store_004,Mango Juice,September 2024,9,65,5.05,1318,328.00,4.0,0.76
609,Store_004,Mango Juice,October 2024,10,239,4.78,1391,1141.98,3.5,0.77
610,Store_004,Mango Juice,November 2024,11,104,3.36,1402,349.01,3.0,0.61
611,Store_004,Mango Juice,December 2024,12,78,6.13,1800,478.26,4.9,0.98
768,Store_005,Orange Juice,January 2024,1,83,4.40,1621,365.18,3.1,0.98
769,Store_005,Orange Juice,February 2024,2,64,3.09,1666,197.70,4.9,0.90
770,Store_005,Orange Juice,March 2024,3,89,2.53,2459,225.60,3.3,0.68
771,Store_005,Orange Juice,April 2024,4,142,3.43,2113,487.06,3.3,0.70
772,Store_005,Orange Juice,May 2024,5,174,3.71,1727,645.53,5.0,0.67
773,Store_005,Orange Juice,June 2024,6,131,3.87,1847,507.05,4.7,0.66
774,Store_005,Orange Juice,July 2024,7,179,5.82,1128,1041.29,4.4,0.85
775,Store_005,Orange Juice,August 2024,8,241,4.82,1017,1162.29,4.0,0.66
776,Store_005,Orange Juice,September 2024,9,161,3.20,1171,514.71,4.8,0.78
777,Store_005,Orange Juice,October 2024,10,283,5.79,1408,1638.44,3.1,0.77
778,Store_005,Orange Juice,November 2024,11,190,3.89,1332,738.77,4.1,1.00
779,Store_005,Orange Juice,December 2024,12,155,3.76,1698,582.10,4.1,0.94
792,Store_005,Mango Juice,January 2024,1,130,3.11,847,404.07,3.9,0.74
793,Store_005,Mango Juice,February 2024,2,107,3.45,817,368.97,4.9,0.98
794,Store_005,Mango Juice,March 2024,3,108,3.45,1051,372.88,4.8,0.79
795,Store_005,Mango Juice,April 2024,4,266,5.31,963,1412.45,4.2,0.90
796,Store_005,Mango Juice,May 2024,5,79,6.50,895,513.36,4.5,0.76
797,Store_005,Mango Juice,June 2024,6,62,5.20,876,322.25,4.5,0.62
798,Store_005,Mango Juice,July 2024,7,260,4.96,697,1289.73,4.8,0.80
799,Store_005,Mango Juice,August 2024,8,264,5.01,573,1321.40,3.6,0.94
800,Store_005,Mango Juice,September 2024,9,160,3.14,635,502.83,3.0,0.78
801,Store_005,Mango Juice,October 2024,10,64,4.36,513,279.21,4.5,0.97
802,Store_005,Mango Juice,November 2024,11,204,3.19,576,651.57,3.8,0.92
803,Store_005,Mango Juice,December 2024,12,188,4.77,741,897.49,4.3,0.68
960,Store_006,Orange Juice,January 2024,1,127,3.48,2775,442.39,3.7,1.00
961,Store_006,Orange Juice,February 2024,2,220,2.69,2961,591.34,4.9,0.64
962,Store_006,Orange Juice,March 2024,3,108,2.52,2601,271.81,4.3,0.86
963,Store_006,Orange Juice,April 2024,4,160,4.15,2659,664.75,4.3,0.83
964,Store_006,Orange Juice,May 2024,5,298,2.89,2036,862.32,4.9,0.84
965,Store_006,Orange Juice,June 2024,6,225,2.96,2389,665.78,4.0,0.67
966,Store_006,Orange Juice,July 2024,7,131,5.69,1526,745.40,4.4,0.82
967,Store_006,Orange Juice,August 2024,8,112,5.63,1604,630.17,3.9,0.85
968,Store_006,Orange Juice,September 2024,9,196,6.47,1622,1268.13,3.5,0.95
969,Store_006,Orange Juice,October 2024,10,221,4.46,1834,985.55,4.3,0.90
970,Store_006,Orange Juice,November 2024,11,233,5.70,1944,1327.32,3.7,0.89
971,Store_006,Orange Juice,December 2024,12,236,3.99,2118,941.28,4.0,0.63
984,Store_006,Mango Juice,January 2024,1,148,2.74,1270,406.05,3.1,0.89
985,Store_006,Mango Juice,February 2024,2,137,4.59,1511,628.21,4.8,0.68
986,Store_006,Mango Juice,March 2024,3,175,4.81,1335,841.48,4.8,0.84
987,Store_006,Mango Juice,April 2024,4,260,4.95,1798,1286.11,3.6,0.70
988,Store_006,Mango Juice,May 2024,5,274,3.58,1359,979.60,3.4,0.70
989,Store_006,Mango Juice,June 2024,6,174,4.88,1171,848.46,4.2,0.63
990,Store_006,Mango Juice,July 2024,7,284,2.85,1222,809.73,3.3,0.81
991,Store_006,Mango Juice,August 2024,8,237,2.56,832,606.35,3.7,0.84
992,Store_006,Mango Juice,September 2024,9,217,5.18,848,1123.08,4.6,0.97
993,Store_006,Mango Juice,October 2024,10,148,4.73,759,699.98,4.4,0.87
994,Store_006,Mango Juice,November 2024,11,160,5.22,1212,834.60,4.9,1.00
995,Store_006,Mango Juice,December 2024,12,144,3.03,1381,436.57,4.3,0.73
1152,Store_007,Orange Juice,January 2024,1,59,4.33,2402,255.29,3.7,0.62
1153,Store_007,Orange Juice,February 2024,2,59,5.34,2752,314.98,5.0,0.62
1154,Store_007,Orange Juice,March 2024,3,141,6.35,2430,894.74,4.3,0.91
1155,Store_007,Orange Juice,April 2024,4,194,5.60,2335,1086.00,3.3,0.79
1156,Store_007,Orange Juice,May 2024,5,215,4.33,2671,930.57,3.6,0.82
1157,Store_007,Orange Juice,June 2024,6,297,6.07,1883,1803.75,3.9,0.81
1158,Store_007,Orange Juice,July 2024,7,59,4.54,1877,267.78,4.8,0.91
1159,Store_007,Orange Juice,August 2024,8,141,6.21,1641,875.28,4.9,0.80
1160,Store_007,Orange Juice,September 2024,9,231,6.06,1530,1400.27,3.5,0.79
1161,Store_007,Orange Juice,October 2024,10,106,3.62,1533,383.30,3.8,1.00
1162,Store_007,Orange Juice,November 2024,11,70,4.07,1557,284.83,3.9,0.89
1163,Store_007,Orange Juice,December 2024,12,286,3.54,2102,1011.06,3.6,0.63
1176,Store_007,Mango Juice,January 2024,1,216,5.99,2970,1293.86,3.5,0.78
1177,Store_007,Mango Juice,February 2024,2,211,3.99,3324,841.50,3.2,0.78
1178,Store_007,Mango Juice,March 2024,3,250,3.48,2807,869.00,4.9,0.98
1179,Store_007,Mango Juice,April 2024,4,269,5.26,2554,1415.07,4.7,0.73
1180,Store_007,Mango Juice,May 2024,5,243,4.60,2996,1118.86,4.4,0.71
1181,Store_007,Mango Juice,June 2024,6,215,2.93,2468,629.01,4.6,0.66
1182,Store_007,Mango Juice,July 2024,7,144,4.46,2106,642.83,3.6,0.68
1183,Store_007,Mango Juice,August 2024,8,189,4.56,1541,861.15,4.6,0.81
1184,Store_007,Mango Juice,September 2024,9,66,3.47,1667,228.78,4.4,0.89
1185,Store_007,Mango Juice,October 2024,10,296,4.48,1740,1327.31,3.0,0.80
1186,Store_007,Mango Juice,November 2024,11,228,3.34,2289,762.40,4.7,0.61
1187,Store_007,Mango Juice,December 2024,12,291,3.74,2565,1087.95,4.9,0.87
1344,Store_008,Orange Juice,January 2024,1,165,3.70,1845,611.28,3.5,0.75
1345,Store_008,Orange Juice,February 2024,2,127,4.30,1828,546.13,3.4,0.83
1346,Store_008,Orange Juice,March 2024,3,195,2.71,2216,528.70,4.3,0.62
1347,Store_008,Orange Juice,April 2024,4,275,6.04,2299,1661.62,3.0,0.95
1348,Store_008,Orange Juice,May 2024,5,115,3.78,1903,434.16,4.2,0.68
1349,Store_008,Orange Juice,June 2024,6,205,4.06,1362,831.90,3.5,0.61
1350,Store_008,Orange Juice,July 2024,7,137,3.04,1291,416.82,3.3,0.88
1351,Store_008,Orange Juice,August 2024,8,83,6.50,1259,539.45,3.0,0.86
1352,Store_008,Orange Juice,September 2024,9,67,5.87,964,393.21,3.4,0.63
1353,Store_008,Orange Juice,October 2024,10,200,6.08,1287,1215.21,4.0,0.71
1354,Store_008,Orange Juice,November 2024,11,91,3.53,1513,321.61,3.7,0.76
1355,Store_008,Orange Juice,December 2024,12,155,6.06,1320,938.53,4.4,0.70
1368,Store_008,Mango Juice,January 2024,1,172,3.90,3279,670.80,4.9,0.63
1369,Store_008,Mango Juice,February 2024,2,275,6.35,3159,1745.27,4.6,0.85
1370,Store_008,Mango Juice,March 2024,3,55,3.28,3333,180.39,4.7,0.83
1371,Store_008,Mango Juice,April 2024,4,284,4.04,3422,1146.16,3.9,0.66
1372,Store_008,Mango Juice,May 2024,5,57,6.37,2378,362.88,3.9,0.66
1373,Store_008,Mango Juice,June 2024,6,248,5.37,2350,1332.13,5.0,0.88
1374,Store_008,Mango Juice,July 2024,7,239,2.83,1917,677.09,4.4,0.72
1375,Store_008,Mango Juice,August 2024,8,57,2.59,2026,147.45,4.3,0.67
1376,Store_008,Mango Juice,September 2024,9,214,4.00,1766,857.02,3.7,0.81
1377,Store_008,Mango Juice,October 2024,10,66,6.05,2044,399.60,4.0,0.89
1378,Store_008,Mango Juice,November 2024,11,82,6.23,1936,511.16,4.4,0.83
1379,Store_008,Mango Juice,December 2024,12,59,5.24,2604,309.16,4.4,0.74
1536,Store_009,Orange Juice,January 2024,1,285,3.11,2318,887.70,4.7,0.71
1537,Store_009,Orange Juice,February 2024,2,60,5.08,2904,305.05,3.3,0.97
1538,Store_009,Orange Juice,March 2024,3,165,5.64,2757,930.60,4.6,0.65
1539,Store_009,Orange Juice,April 2024,4,118,4.61,2744,543.86,4.9,0.79
1540,Store_009,Orange Juice,May 2024,5,227,6.05,2548,1373.66,3.9,0.82
1541,Store_009,Orange Juice,June 2024,6,138,6.27,2139,865.71,4.0,0.87
1542,Store_009,Orange Juice,July 2024,7,201,4.30,2101,864.34,3.7,0.76
1543,Store_009,Orange Juice,August 2024,8,123,3.23,1477,397.50,3.7,0.77
1544,Store_009,Orange Juice,September 2024,9,240,3.39,1634,812.59,4.6,0.62
1545,Store_009,Orange Juice,October 2024,10,274,4.73,1924,1295.15,4.5,0.73
1546,Store_009,Orange Juice,November 2024,11,256,4.34,2091,1111.11,3.6,0.61
1547,Store_009,Orange Juice,December 2024,12,60,4.97,2305,298.46,3.6,0.63
1560,Store_009,Mango Juice,January 2024,1,145,3.38,2036,489.55,3.9,0.85
1561,Store_009,Mango Juice,February 2024,2,274,3.46,2353,947.23,3.6,0.93
1562,Store_009,Mango Juice,March 2024,3,196,4.57,2265,896.37,3.9,0.73
1563,Store_009,Mango Juice,April 2024,4,147,2.78,2192,408.72,4.7,0.80
1564,Store_009,Mango Juice,May 2024,5,273,2.71,1891,739.25,4.7,0.78
1565,Store_009,Mango Juice,June 2024,6,137,6.12,1525,838.42,4.6,0.74
1566,Store_009,Mango Juice,July 2024,7,171,2.89,1609,493.72,4.0,1.00
1567,Store_009,Mango Juice,August 2024,8,285,4.09,1382,1165.96,3.6,0.99
1568,Store_009,Mango Juice,September 2024,9,172,5.58,1007,960.60,3.5,0.97
1569,Store_009,Mango Juice,October 2024,10,298,3.08,1294,917.76,3.5,0.97
1570,Store_009,Mango Juice,November 2024,11,195,4.52,1211,881.35,3.4,0.93
1571,Store_009,Mango Juice,December 2024,12,90,3.40,1714,305.84,3.9,0.71
1728,Store_010,Orange Juice,January 2024,1,136,4.39,1494,597.22,4.3,0.64
1729,Store_010,Orange Juice,February 2024,2,144,3.21,1487,462.79,3.2,0.98
1730,Store_010,Orange Juice,March 2024,3,178,2.92,1424,520.33,4.3,0.64
1731,Store_010,Orange Juice,April 2024,4,149,5.58,1279,830.97,4.2,0.73
1732,Store_010,Orange Juice,May 2024,5,232,2.95,1261,684.99,3.7,1.00
1733,Store_010,Orange Juice,June 2024,6,73,3.95,1400,288.65,4.3,0.96
1734,Store_010,Orange Juice,July 2024,7,290,6.12,891,1774.08,4.9,1.00
1735,Store_010,Orange Juice,August 2024,8,196,3.62,1001,708.64,4.9,0.63
1736,Store_010,Orange Juice,September 2024,9,297,5.64,883,1674.75,4.7,0.97
1737,Store_010,Orange Juice,October 2024,10,120,3.10,1033,372.15,3.1,0.95
1738,Store_010,Orange Juice,November 2024,11,293,6.43,953,1883.29,4.8,0.65
1739,Store_010,Orange Juice,December 2024,12,207,4.92,982,1017.72,4.9,0.69
1752,Store_010,Mango Juice,January 2024,1,110,5.61,3521,616.69,4.6,0.62
1753,Store_010,Mango Juice,February 2024,2,292,3.48,3564,1016.90,3.2,0.92
1754,Store_010,Mango Juice,March 2024,3,131,3.58,2956,468.48,4.6,0.81
1755,Store_010,Mango Juice,April 2024,4,242,3.57,2802,864.69,3.1,0.88
1756,Store_010,Mango Juice,May 2024,5,111,5.72,3054,635.27,3.5,0.79
1757,Store_010,Mango Juice,June 2024,6,295,3.01,2937,887.73,3.4,0.98
1758,Store_010,Mango Juice,July 2024,7,126,5.60,2480,705.00,3.7,0.67
1759,Store_010,Mango Juice,August 2024,8,135,4.71,2119,635.49,4.3,0.70
1760,Store_010,Mango Juice,September 2024,9,70,6.36,2236,445.38,3.0,0.79
1761,Store_010,Mango Juice,October 2024,10,194,3.34,1871,647.43,3.5,0.65
1762,Store_010,Mango Juice,November 2024,11,115,5.24,2501,603.00,4.7,0.70
1763,Store_010,Mango Juice,December 2024,12,128,4.63,2827,592.83,4.9,0.98

In [ ]:
## Analyizing Market Performance :Reorder_Rate for "Orange Juice" And "Mango Juice" that are Equal 0.6

In [23]:
juice5=jusice_dataframe[(jusice_dataframe["Juice_Type"]=="Mango Juice")&(jusice_dataframe["Reorder_Rate"]==0.6)|(jusice_dataframe["Juice_Type"]=="Orange Juice")&(jusice_dataframe["Reorder_Rate"]==0.6)]

In [24]:
juice5

,Store_ID,Juice_Type,Month,Month_Number,Units_Sold,Price_Per_Unit,Monthly_Sales,Revenue,Customer_Satisfaction,Reorder_Rate
578,Store_004,Orange Juice,March 2024,3,195,5.04,1651,982.35,4.5,0.6